const playlist = [
  { id: "fJ9rUzIMcZQ", title: "Queen – Bohemian Rhapsody (Official Video Remastered)" },
  { id: "1w7OgIMMRc4", title: "Guns N' Roses - Sweet Child O' Mine (Official Music Video)" },
  { id: "hTWKbfoikeg", title: "Nirvana - Smells Like Teen Spirit (Official Music Video)" },
  { id: "EcPsB6PwaiE", title: "John Lennon - Imagine (Remastered 2020)" },
  { id: "tbkOZTSvrHs", title: "John Farnham - You're the Voice" },
  { id: "X791IzOwt3Q", title: "Stairway to Heaven (Remaster)" },
  { id: "GChhRrU6BJU", title: "AC/DC - It's a Long Way to the Top (If You Wanna Rock 'N' Roll) (Audio)" },
  { id: "uQy3y9Ox0gE", title: "Thriller [Single Version] - Michael Jackson" },
  { id: "MSSxnv1_J2g", title: "[I Can't Get No] Satisfaction" },
  { id: "xFrGuyw1V8s", title: "ABBA - Dancing Queen (Official Music Video)" },
  { id: "lDK9QqIzhwk", title: "Bon Jovi - Livin' On A Prayer" },
  { id: "dnqxbdnzlhw", title: "The Easybeats - Friday On My Mind (French TV, 1967) 1080p HD" },
  { id: "s__rX_WL100", title: "Madonna - Like A Virgin (Official Video)" },
  { id: "oMfjgQ8ptrE", title: "Good Vibrations (Remastered 2001)" },
  { id: "rm9coqlk8fY", title: "Bob Dylan - Knockin' On Heaven's Door (Official Audio)" },
  { id: "izGwDsrQ1eQ", title: "George Michael - Careless Whisper (Official Video)" },
  { id: "e3-5YC_oHjE", title: "U2 - I Still Haven't Found What I'm Looking For (Official Music Video)" },
  { id: "6FOUqQt3Kg0", title: "Aretha Franklin - Respect [1967] (Aretha's Original Version)" },
  { id: "3JWTaaS7LdU", title: "Whitney Houston - I Will Always Love You (Official 4K Video)" },
  { id: "8UVNT4wvIGY", title: "Gotye - Somebody That I Used To Know (feat. Kimbra) [Official Music Video]" },
  { id: "AQOlwMKpmvQ", title: "Crowded House - Better Be Home Soon (Official Video)" },
  { id: "qoX6AKuYWL8", title: "Light My Fire (2017 Remaster)" },
  { id: "XfR9iY5y94s", title: "Men At Work - Down Under (Official HD Video)" },
  { id: "vU05Eksc_iM", title: "Oasis - Wonderwall (Official HD Remastered Video)" },
  { id: "H-kA3UtBj4M", title: "Marvin Gaye - What's Going On" },
  { id: "inKlN0ScObA", title: "Cold Chisel - Khe Sanh [Official Video]" },
  { id: "fNFzfwLM72c", title: "Bee Gees - Stayin' Alive (Official Music Video)" },
  { id: "4m1EFMoRFvY", title: "Beyoncé - Single Ladies (Put a Ring on It) (Video Version)" },
  { id: "gJLIiF15wjQ", title: "Spice Girls - Wannabe (Official Music Video)" },
  { id: "0CFuCYNx-1g", title: "Stevie Wonder Superstition" },
  { id: "c18441Eh_WE", title: "Kylie Minogue - Can't Get You Out Of My Head (Official Video)" },
  { id: "GLvohMXgcBo", title: "Red Hot Chili Peppers - Under The Bridge [Official Music Video]" },
  { id: "_wO8toxinoc", title: "Meat Loaf - You Took The Words Right Out Of My Mouth (Hot Summer Night) (PCM Stereo)" },
  { id: "JmcA9LIIXWw", title: "Culture Club - Karma Chameleon (Official Music Video)" },
  { id: "luwAMFcc2f8", title: "Robbie Williams - Angels" },
  { id: "0xGPi-Al3zQ", title: "Rhiannon" },
  { id: "CD-E-LDc384", title: "Metallica: Enter Sandman (Official Music Video)" },
  { id: "CpKyFTYvhpU", title: "Elvis Presley "Don't Be Cruel" (January 6, 1957) on The Ed Sullivan Show" },
  { id: "F93ywiGMDnQ", title: "INXS - Need You Tonight (Official Music Video)" },
  { id: "iYYRH4apXDo", title: "David Bowie – Space Oddity (Official Video)" },
  { id: "3MMXjunSx80", title: "Jeff Buckley - Last Goodbye (Edit)" },
  { id: "PIb6AZdTr-A", title: "Cyndi Lauper - Girls Just Want To Have Fun (Official Video)" },
  { id: "HrxX9TBj2zY", title: "Pink Floyd - Another Brick In The Wall, Part Two (Official Music Video)" },
  { id: "psTq_J-JwNI", title: "Yothu Yindi - Treaty (Radio Mix)" },
  { id: "y5ecvBaqHBk", title: "Don McLean - American Pie" },
  { id: "0-EF60neguk", title: "Sinéad O'Connor - Nothing Compares 2 U (Official Music Video) [HD]" },
  { id: "j13oJajXx0M", title: "Carly Simon - You're So Vain" },
  { id: "TLV4_xaYynY", title: "The Jimi Hendrix Experience - All Along The Watchtower (Official Audio)" },
  { id: "CnQ8N1KacJc", title: "Green Day - Good Riddance (Time of Your Life) [Official Music Video] [4K UPGRADE]" },
  { id: "StKVS0eI85I", title: "Blondie - Call me" },
  { id: "OPf0YbXqDm0", title: "Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars" },
  { id: "nqxVMLVe62U", title: "The Jacksons - Blame It On the Boogie (Official Video)" },
  { id: "uq-gYOrU8bA", title: "Paul Simon - You Can Call Me Al (Official Video)" },
  { id: "5-hDK76bIps", title: "Hunters & Collectors - Throw Your Arms Around Me (Official Video)" },
  { id: "gxEPV4kolz0", title: "Billy Joel - Piano Man (Official HD Video)" },
  { id: "t3TPmPOrDEk", title: "Jimmy Barnes - Working Class Man (Official Video)" },
  { id: "eJO5HU_7_1w", title: "Eminem - The Real Slim Shady (Official Video - Clean Version)" },
  { id: "zuuObGsB0No", title: "Joy Division - Love Will Tear Us Apart [OFFICIAL MUSIC VIDEO]" },
  { id: "WQnAxOQxQIU", title: "Savage Garden - Truly Madly Deeply" },
  { id: "CduA0TULnow", title: "Britney Spears - Oops!...I Did It Again (Official HD Video)" },
  { id: "bbr60I0u2Ng", title: "The Knack - My Sharona (Official Music Video)" },
  { id: "xwtdhWltSIg", title: "R.E.M. - Losing My Religion (Official HD Music Video)" },
  { id: "yYcyacLRPNs", title: "Elton John - Tiny Dancer" },
  { id: "EPhWR4d3FJQ", title: "Bruce Springsteen - Born in the U.S.A. (Official Video)" },
  { id: "ydrtF45-y-g", title: "Salt-N-Pepa - Let's Talk About Sex (Official Music Video)" },
  { id: "oQfAZVsz6KM", title: "Daddy Cool - Eagle Rock  - Clip (1971)" },
  { id: "HM_eb0vVo0k", title: "Powderfinger - My Happiness (Official Video)" },
  { id: "A_MjCqQoLLA", title: "The Beatles - Hey Jude" },
  { id: "qM0zINtulhM", title: "Pearl Jam - Alive (Official Video)" },
  { id: "rYEDA3JcQqw", title: "Adele - Rolling in the Deep (Official Music Video)" },
  { id: "zNW2XkvaL6U", title: "Beds Are Burning (Remastered)" },
  { id: "zFYEYRcjK2g", title: "Creep" },
  { id: "BWEKw5xG69M", title: "Take That - Back For Good (Radio Mix) HQ" },
  { id: "3mkidP2OUCk", title: "Icehouse - Great Southern Land" },
  { id: "d020hcWA_Wg", title: "Coldplay - Clocks (Official Video)" },
  { id: "WnrE0yN2uLY", title: "I Will Survive (Rerecorded)" },
  { id: "oKOtzIo-uYw", title: "Fugees - Killing Me Softly With His Song (Official Video)" },
  { id: "OMOGaugKpzs", title: "The Police - Every Breath You Take (Official Music Video)" },
  { id: "CoOp12ayIVg", title: "Tears in Heaven (Acoustic Live)" },
  { id: "KCjMZMxNr-0", title: "Duran Duran - Girls On Film (Official Music Video)" },
  { id: "wBVJFGxyxgE", title: "The Real Thing -  Russell Morris" },
  { id: "NHozn0YXAeE", title: "Hanson - MMMBop (Official Music Video)" },
  { id: "eBG7P-K-r1Y", title: "Foo Fighters - Everlong (Official HD Video)" },
  { id: "pIgZ7gMze7A", title: "Wham! - Wake Me Up Before You Go-Go (Official Video)" },
  { id: "KUmZp8pR1uc", title: "Amy Winehouse - Rehab" },
  { id: "8LhCd1W2V0Q", title: "Lenny Kravitz - Are You Gonna Go My Way (Official Music Video)" },
  { id: "tdkROH7Exyg", title: "The Who - My Generation (Original Mono Version) HD" },
  { id: "1lyu1KKwC74", title: "The Verve - Bitter Sweet Symphony" },
  { id: "47P3bzefCVI", title: "Silverchair - Straight Lines (Official Video)" },
  { id: "NPcyTyilmYY", title: "Alanis Morissette - You Oughta Know (Official 4K Music Video)" },
  { id: "Zi_XLOBDo_Y", title: "Michael Jackson - Billie Jean (Official Video)" },
  { id: "lp-EO5I60KA", title: "Ed Sheeran - Thinking Out Loud (Official Music Video)" },
  { id: "4F_RCWVoL4s", title: "Neil Diamond - Sweet Caroline (Audio)" },
  { id: "wTP2RUD_cL0", title: "Dire Straits - Money For Nothing (Official Music Video)" },
  { id: "SSbBvKaM6sk", title: "Blur - Song 2 (Official Music Video)" },
  { id: "n0pcM30pjgQ", title: "Split Enz - Message To My Girl (Official Video)" },
  { id: "fDxzQJaA228", title: "George Michael, Aretha Franklin - I Knew You Were Waiting (For Me) (Official Video)" },
  { id: "4RdATJ_6870", title: "Stand By Me (Remastered 2010)" },
  { id: "djV11Xbc914", title: "a-ha - Take On Me (Official Video) [Remastered in 4K]" },
  { id: "oG6fayQBm9w", title: "Lou Reed - Walk on the Wild Side (Official Audio)" },
  { id: "VlWiQ69DGE0", title: "Them - Gloria (Audio) ft. Van Morrison" },
  { id: "t1CvS7aOMa4", title: "Angie (Remastered)" },
  { id: "ZR-eTR3Dcps", title: "Paul Kelly - Dumb Things (Official Video)" },
  { id: "E2Ru4_A8INU", title: "Blue Sky Mine (2011 Remaster)" },
  { id: "MYU3F8uUGiw", title: "Candle In The Wind (Remastered 2014)" },
  { id: "ujNeHIo7oTE", title: "U2 - With Or Without You (Official Music Video)" },
  { id: "unfzfe8f9NI", title: "ABBA - Mamma Mia (Official Music Video)" },
  { id: "SUGlWCCVA4M", title: "Cold Chisel - Cheap Wine [Official Video]" },
  { id: "RaNEVlz89f8", title: "The Horses (2017 Remastered)" },
  { id: "PWgvGjAhvIw", title: "Outkast - Hey Ya! (Official HD Video)" },
  { id: "FJ-r0bilzhU", title: "Elvis Presley - In the Ghetto (Official Audio)" },
  { id: "ZG_k5CSYKhg", title: "Faith No More - Epic (Official Music Video)" },
  { id: "ViwtNLUqkMY", title: "Beyoncé - Crazy In Love ft. JAY Z" },
  { id: "v2AC41dglnM", title: "AC/DC - Thunderstruck (Official Video)" },
  { id: "IHknoSQZibU", title: "Madonna - Holiday [Audio]" },
  { id: "ag8XcMG1EX4", title: "Crowded House - Weather With You" },
  { id: "5oWyMakvQew", title: "Dreams (2004 Remaster)" },
  { id: "aaYpQVsifvI", title: "Changes (2015 Remaster)" },
  { id: "Jne9t8sHpUc", title: "Alanis Morissette - Ironic (Official 4K Music Video)" },
  { id: "wqPlb5PLBvg", title: "The Who - You Better You Bet (Promo Video)" },
  { id: "vHXjcdNIN-Q", title: "L.A. Woman" },
  { id: "KrZHPOeOxQQ", title: "Bon Jovi - You Give Love A Bad Name" },
  { id: "hajBdDM2qdg", title: "Marvin Gaye - I Heard It Through The Grapevine" },
  { id: "ZhIsAZO5gl0", title: "Kiss - I Was Made For Lovin' You" },
  { id: "ltrMfT4Qz5Y", title: "Kenny Loggins - Footloose (Official Video)" },
  { id: "ma2lQ3c-FuA", title: "Stevie Wright - Evie (Let Your Hair Hang Down) (part 1) • TopPop" },
  { id: "JZjWGsAUnkI", title: "Backstreet Boys - Everybody (Backstreet's Back) (Extended Version)" },
  { id: "wpqm-05R2Jk", title: "The Avalanches - Since I Left You" },
  { id: "vabnZ9-ex7o", title: "Nirvana - Come As You Are (Official Music Video)" },
  { id: "DfDt-KKHIaU", title: "The Police-Roxanne [Remastered 2003]" },
  { id: "LPn0KFlbqX8", title: "Cyndi Lauper - True Colors (Official HD Video)" },
  { id: "2ROiU9kOHeE", title: "Crowded House - Fall At Your Feet" },
  { id: "MpMwMDqOprc", title: "The Saints - (I'm) Stranded [HQ]" },
  { id: "RF0HhrwIwp0", title: "Kings Of Leon - Sex on Fire (Official Video)" },
  { id: "oRdxUFDoQe0", title: "Michael Jackson - Beat It (Official 4K Video)" },
  { id: "pTdihu-mp90", title: "James Brown - I Got You (I Feel Good) (Visualizer)" },
  { id: "Lo2qQmj0_h4", title: "AC/DC - You Shook Me All Night Long (Official 4K Video)" },
  { id: "MQcPB1WkISI", title: "Living Colour - Love Rears Its Ugly Head" },
  { id: "H0Ww6TkAwoQ", title: "Love Is A Battlefield (Remastered 2005)" },
  { id: "_W44NZvHc9I", title: "Empire State of Mind (Part II) Broken Down" },
  { id: "R9L1O426uF8", title: "Don't Let the Sun Go Down on Me" },
  { id: "PTULqzrhBWA", title: "INXS - Original Sin (Official Music Video)" },
  { id: "Jv4et3RIMcg", title: "Lola (2014 Remaster)" },
  { id: "1tLYYSofs3U", title: "Another One Bites The Dust (Remastered 2011)" },
  { id: "FrLequ6dUdM", title: "TLC - No Scrubs (Official HD Video)" },
  { id: "hic-dnps6MU", title: "The Rolling Stones - Miss You - OFFICIAL PROMO" },
  { id: "94bdMSCdw20", title: "Big Yellow Taxi - Joni Mitchell" },
  { id: "qQvr2eF5zMM", title: "The Unguarded Moment (2002 Remastered)" },
  { id: "wv-34w8kGPM", title: "Divinyls - I Touch Myself (Official Music Video)" },
  { id: "wMsazR6Tnf8", title: ""I Love Rock 'n' Roll" - Joan Jett & the Blackhearts (Official Video)" },
  { id: "TYQzIw0zat0", title: "You Got It" },
  { id: "lDpnjE1LUvE", title: "Nick Cave & The Bad Seeds ft. Kylie Minogue - Where The Wild Roses Grow (Official HD Video)" },
  { id: "XpqqjU7u5Yc", title: "Bee Gees - How Deep Is Your Love (Official Video)" },
  { id: "H9tEvfIsDyo", title: "Prince & The Revolution - Kiss (Official Music Video)" },
  { id: "etviGf1uWlg", title: "Deee-Lite - Groove Is In The Heart (Official Video)" },
  { id: "Rbm6GXllBiw", title: "Guns N' Roses - Paradise City (Official Music Video)" },
  { id: "HoS1Fr9G46I", title: "When The War Is Over (2011 Remastered)" },
  { id: "UvEmwYg6aFw", title: "We Will Rock You (Remastered) (Queen)" },
  { id: "CdqoNKCCt7A", title: "Simple Minds - Don't You (Forget About Me)" },
  { id: "iG7XifX5JhY", title: "Whole Lotta Love (Remaster)" },
  { id: "TxcDTUMLQJI", title: "U2 - Mysterious Ways (Official Music Video)" },
  { id: "PivWY9wn5ps", title: "Michael Jackson - Man In The Mirror (Official Video)" },
  { id: "umAurdHLNzU", title: "Alicia Bridges - I Love The Nightlife (1978)" },
  { id: "god7hAPv8f0", title: "Earth, Wind & Fire - Boogie Wonderland (Official Video)" },
  { id: "towUVNELZBI", title: "The Boys Light Up (Remastered)" },
  { id: "8AHCfZTRGiI", title: "Johnny Cash - Hurt" },
  { id: "wo1OwRTRKRk", title: "Elton John - Bennie And The Jets (Official Music Video)" },
  { id: "JAwk7yBQxDs", title: "Too Funky (Single Edit)" },
  { id: "4BQLE_RrTSU", title: "Bill Medley, Jennifer Warnes - (I've Had) The Time Of My Life (Official HD Video)" },
  { id: "eLZghQtxeSA", title: "John Fogerty - Lookin' Out My Backdoor (Live - 2005)" },
  { id: "2nXGPZaTKik", title: "Culture Club - Do You Really Want To Hurt Me" },
  { id: "jsjdjWGDvFk", title: "AC/DC - Dirty Deeds Done Dirt Cheap (Official Audio)" },
  { id: "Y0pdQU87dc8", title: "Bryan Adams - (Everything I Do) I Do It For You" },
  { id: "vTv9z0ynDWc", title: "Ego Is Not a Dirty Word (2015 Remaster)" },
  { id: "tAGnKpE4NCI", title: "Metallica: Nothing Else Matters (Official Music Video)" },
  { id: "0H6re3PCP3E", title: "Pretenders - Brass In Pocket (Official Music Video)" },
  { id: "gHTcQB_4AFw", title: "Hot Chocolate - Every 1’s A Winner (ZDF Disco, 12.06.1978)" },
  { id: "OqSrEhuWrgY", title: "Jimmy Barnes - Good Times" },
  { id: "UrIiLvg58SY", title: "Extreme - More Than Words (Official Music Video)" },
  { id: "fAb8Q9X2xAc", title: "Blondie - The Tide Is High" },
  { id: "XEjLoHdbVeE", title: "ABBA - Gimme! Gimme! Gimme! (A Man After Midnight)" },
  { id: "bpZvg_FjL3Q", title: "Bob Dylan - Hurricane (Official Audio)" },
  { id: "JnfyjwChuNU", title: "Red Hot Chili Peppers - By The Way [Official Music Video]" },
  { id: "4aXkA6X_zsA", title: "China Girl (2018 Remaster)" },
  { id: "V6hQ9HSKlIE", title: "Tracy Chapman - Give Me One Reason (Official Music Video)" },
  { id: "PNbBDrceCy8", title: "The Who - Who Are You (Promo Video)" },
  { id: "oXqPjx94YMg", title: "k.d. lang - Constant Craving (Official Music Video) | Warner Vault" },
  { id: "7qFfFVSerQo", title: "Radiohead - High and Dry" },
  { id: "6Ejga4kJUts", title: "The Cranberries - Zombie (Official Music Video)" },
  { id: "oAZLgsDRUv4", title: "Dusty Springfield - Son of a Preacher Man (Official Audio)" },
  { id: "CS9OO0S5w2k", title: "Village People - YMCA (OFFICIAL Music Video 1978)" },
  { id: "G333Is7VPOg", title: "Madonna - Papa Don't Preach (Official Video) [HD]" },
  { id: "Wm54XyLwBAk", title: "Oasis - Morning Glory (Official HD Remastered Video)" },
  { id: "XZVpR3Pk-r8", title: "Soft Cell - Tainted Love (Official Music Video)" },
  { id: "TFIrKWg89r4", title: "Split Enz - I See Red (Official Video)" },
  { id: "WfunypXsBO4", title: "Where The Streets Have No Name (Remastered)" },
  { id: "CxKWTzr-k6s", title: "Pearl Jam - Even Flow (Official Video)" },
  { id: "oe2hdbft5-U", title: "I Shot The Sheriff (1973) - Bob Marley & The Wailers" },
  { id: "Z0GFRcFm-aY", title: "R.E.M. - It's The End Of The World As We Know It (And I Feel Fine)" },
  { id: "bgghy8gmCvQ", title: "I´d Do Anything For Love (Complete Version Live) Meat Loaf" },
  { id: "T0spQCw35D4", title: "Nick Cave & The Bad Seeds - The Ship Song" },
  { id: "xvqeSJlgaNk", title: "The Monkees - Daydream Believer (Official Music Video)" },
  { id: "e7tWqyM3r-g", title: "The Clash - Should I Stay or Should I Go (Remastered)" },
  { id: "A_J2bcNx3Gw", title: "Summer Nights (From “Grease”)" },
  { id: "yugLWxoX7qQ", title: "Sisters Are Doin' It for Themselves (Remastered)" },
  { id: "JkK8g6FMEXE", title: "Aerosmith - I Don't Want to Miss a Thing (Official HD Video)" },
  { id: "LrjHz5hrupA", title: "Elvis Costello & The Attractions - Oliver's Army" },
  { id: "LvdLovAaYzM", title: "Martika - Toy Soldiers" },
  { id: "uSD4vsh1zDA", title: "The Black Eyed Peas - I Gotta Feeling (Official Music Video)" },
  { id: "lelsyP9qL2I", title: "Cold Chisel - Saturday Night [Official Video]" },
  { id: "-35W_FWCT9Q", title: "Lynyrd Skynyrd - Sweet Home Alabama (Audio)" },
  { id: "eOUtsybozjg", title: "Bon Jovi - Bad Medicine (Official Music Video)" },
  { id: "6jC9Insyzgc", title: "Tina Arena - Chains (Official Music Video)" },
  { id: "6vQpW9XRiyM", title: "Bruce Springsteen - Glory Days (Official Video)" },
  { id: "ZSM3w1v-A_Y", title: "Timbaland - Apologize ft. OneRepublic" },
  { id: "ruTMp4_sy1E", title: "The Rolling Stones - Jumpin' Jack Flash (Official Video) [4K]" },
  { id: "9jK-NcRmVcw", title: "Europe - The Final Countdown (Official Video)" },
  { id: "RCaWyhDFYCk", title: "Black or White (Remastered Version)" },
  { id: "Ye7FKc1JQe4", title: "Tears For Fears - Shout (Official Music Video)" },
  { id: "HyMm4rJemtI", title: "David Bowie - Ashes To Ashes (Official Video)" },
  { id: "FoEPrbdfmT4", title: "INXS - What You Need (Official Music Video)" },
  { id: "6vwNcNOTVzY", title: "Kanye West - Gold Digger ft. Jamie Foxx" },
  { id: "0TMoc959LCA", title: "Irene Cara - Flashdance ... What A Feeling (Radio-Edit) Geffen Records 1983" },
  { id: "cBMXQrW3VNA", title: "Killer Queen (Remastered 2011)" },
  { id: "oadhHk2xs6c", title: "Wicked Game" },
  { id: "rUnktL_ZZgo", title: "King Of The Mountain (Remastered)" },
  { id: "HsC_SARyPzk", title: "Phil Collins - A Groovy Kind Of Love (Official Music Video)" },
  { id: "LerRV-CGeFU", title: "Paul Kelly - Before Too Long (Official Video)" },
  { id: "4B_UYYPb-Gk", title: "RUN DMC - Walk This Way (Official HD Video) ft. Aerosmith" },
  { id: "Y5fBdpreJiU", title: "The Killers - Somebody Told Me (Official Music Video)" },
  { id: "ClbmWkbocoY", title: "Sheryl Crow - All I Wanna Do" },
  { id: "GlPlfCy1urI", title: "Elton John - Your Song (Top Of The Pops 1971)" },
  { id: "4aeETEoNfOg", title: "The Smashing Pumpkins - 1979 (Official Music Video)" },
  { id: "-crgQGdpZR0", title: "ABBA - Take A Chance On Me (Official Music Video)" },
  { id: "iQI5fdVCvlU", title: "Hunters & Collectors - Holy Grail (Official Video)" },
  { id: "eHUUMEv2j94", title: "Moody Blues - Nights In White Satin (single version) (1972)" },
  { id: "q-4TkRMEK7Y", title: "Jump (2015 Remaster)" },
  { id: "-oqAU5VxFWs", title: "Counting Crows - Mr. Jones (Official Music Video)" },
  { id: "PiZHNw1MtzI", title: "AC/DC - Who Made Who (Official HD Video)" },
  { id: "hv_zJrO_ptk", title: "INXS - Devil Inside (Official Music Video)" },
  { id: "uE-itlGNap4", title: "Pseudo Echo - Funkytown" },
  { id: "Mr_uHJPUlO8", title: "Red Hot Chili Peppers - Give It Away [Official Music Video]" },
  { id: "jQvUBf5l7Vw", title: "Iggy Pop - Lust For Life" },
  { id: "rblt2EtFfC4", title: "Prince - 1999 (Official Music Video)" },
  { id: "79fzeNUqQbQ", title: "Madonna - Like A Prayer (Official Video)" },
  { id: "2b_KfAGiglc", title: "Janet Jackson - That's The Way Love Goes" },
  { id: "cvn6eYJh-0c", title: "Robbie Williams, Kylie Minogue - Kids" },
  { id: "y2bVIBwpCTA", title: "The Jackson 5 "I Want You Back" on The Ed Sullivan Show" },
  { id: "9lApaQC58r8", title: "Eurythmics, Annie Lennox, Dave Stewart - Who's That Girl (Remastered)" },
  { id: "c4BLVznuWnU", title: "Ed Sheeran - Lego House [Official Music Video]" },
  { id: "hEmH1EgJbEs", title: "En Vogue (with Salt-N-Pepa) - Whatta Man (Official Music Video)" },
  { id: "WGoDaYjdfSg", title: "The Jimi Hendrix Experience - Purple Haze (Official Audio)" },
  { id: "ovo6zwv6DX4", title: "Lionel Richie - Dancing On The Ceiling" },
  { id: "qKn7XAMNV-g", title: "Missy Higgins - Scar (Video)" },
  { id: "Yv3dvVw6p5c", title: "Sweetest Thing" },
  { id: "K1b8AhIsSYQ", title: "Starship - We Built This City (Official Music Video) [HD]" },
  { id: "-Ro8-ngA8gs", title: "Chaka Khan-Ain't Nobody" },
  { id: "CvBfHwUxHIk", title: "Rihanna - Umbrella (Orange Version) (Official Music Video) ft. JAY-Z" },
  { id: "WyBKzBtaKWM", title: "Crowded House - Something So Strong" },
  { id: "HBcq5EzBcmQ", title: "ROBERT PALMER & UB40 I'LL BE YOUR BABY TONIGHT" },
  { id: "xJeWySiuq1I", title: "Ultravox - Vienna (Official Music Video)" },
  { id: "lfVAJNqWw84", title: "The Long And Winding Road (Naked Version / Remastered 2013)" },
  { id: "HAkHqYlqops", title: "Matchbox Twenty - Push (Official Video) [HD Remaster]" },
  { id: "_3eC35LoF4U", title: "Talking Heads - Burning Down the House (Official Video)" },
  { id: "GC5E8ie2pdM", title: "Tina Turner - The Best (Official Music Video) [HD Upgrade]" },
  { id: "ruAi4VBoBSM", title: "Fatboy Slim - Praise You [Official Video]" },
  { id: "AIBv2GEnXlc", title: "INXS - Never Tear Us Apart (Official Music Video)" },
  { id: "SsmVgoXDq2w", title: "The Bangles - Manic Monday (Official Video)" },
  { id: "IUFOVu1CurM", title: "ICEHOUSE - Electric Blue" },
  { id: "BjvfIJstWeg", title: "The Cure - Close To Me" },
  { id: "6s9il0BTI4I", title: "Kylie Minogue - Confide In Me (The Truth Mix)" },
  { id: "aXK71H8c-l0", title: "Queen - I Want To Break Free - (Remastered 2011)" },
  { id: "0hGhl7ki3HM", title: "Don't Stop (2004 Remaster)" },
  { id: "boJhWtw-6Gg", title: "Bruce Springsteen - Hungry Heart (Official Audio)" },
  { id: "ML9h3I5Uktw", title: "GANGgajang - Sounds Of Then (This Is Australia)" },
  { id: "1uYWYWPc9HU", title: "Radiohead - Karma Police" },
  { id: "k0W_ybghFzg", title: "U2 - All I Want Is You (Official Music Video)" },
  { id: "-DlMoJ2V6uk", title: "Bad (2012 Remaster)" },
  { id: "qQzdAsjWGPg", title: "My Way (2008 Remastered)" },
  { id: "FYH8DsU2WCk", title: "New Order - Blue Monday" },
  { id: "yKNxeF4KMsY", title: "Coldplay - Yellow (Official Video)" },
  { id: "04v-SdKeEpE", title: "George Harrison - My Sweet Lord" },
  { id: "Bx51eegLTY8", title: "Berlin - Take My Breath Away (Official Video - Top Gun)" },
  { id: "RqQn2ADZE1A", title: "Aerosmith - Janie's Got A Gun (David Fincher Cut)" },
  { id: "0aqLwHP4y6Q", title: "Toni Basil "Hey Mickey"  Music Video" },
  { id: "u7K72X4eo_s", title: "Massive Attack - Teardrop (Official Video)" },
  { id: "P6FF3-SWwsE", title: "Paul Kelly - To Her Door (Official Video)" },
  { id: "NdYWuo9OFAw", title: "Goo Goo Dolls – Iris [Official Music Video] [4K Remaster]" },
  { id: "Z9EbR0ckb40", title: "Bryan Ferry - Let's Stick Together" },
  { id: "6RUIeX6UCT8", title: "Don Henley - The Boys Of Summer (Official Music Video)" },
  { id: "HMt-nAYKTN0", title: "Björk - It's Oh So Quiet" },
  { id: "h04CH9YZcpI", title: "John Mellencamp - Jack & Diane (Official Music Video)" },
  { id: "I07249JX8w4", title: "Ike & Tina Turner - Nutbush City Limits (1973)" },
  { id: "129kuDCQtHs", title: "Bruce Springsteen - Dancing In the Dark (Official Video)" },
  { id: "8xg3vE8Ie_E", title: "Taylor Swift - Love Story" },
  { id: "Hphwfq1wLJs", title: "Rod Stewart - Da Ya Think I'm Sexy? (Official Video) [HD Remaster]" },
  { id: "pAgnJDJN4VA", title: "AC/DC - Back In Black (Official 4K Video)" },
  { id: "XuY8Ck7-7z8", title: "Under Pressure (Remastered 2011)" },
  { id: "pojL_35QlSI", title: "The Chicks - Not Ready To Make Nice (Official Video)" },
  { id: "tkOr12AQpnU", title: "New Order - Bizarre Love Triangle (Official Music Video) [HD Upgrade]" },
  { id: "XKuJUxGntRI", title: "Amii Stewart - Knock On Wood (Official Video)" },
  { id: "GuJQSAiODqI", title: "Madonna - Vogue (Official Video)" },
  { id: "K8KgP2aOXcA", title: "Cold Chisel - Flame Trees [Official Video]" },
  { id: "rjlSiASsUIs", title: "Marvin Gaye - Sexual Healing (Official HD Video)" },
  { id: "u31FO_4d9TY", title: "N.W.A. - Express Yourself (Official Music Video)" },
  { id: "CIk45fEWBok", title: "Cry Me a River" },
  { id: "SP6BgyF7LPw", title: "Heart Of Glass (Special Mix)" },
  { id: "vCadcBR95oU", title: "Salt-N-Pepa - Push It (Official Music Video)" },
  { id: "XPpTgCho5ZA", title: "Maroon 5 - This Love" },
  { id: "o1tj2zJ2Wvg", title: "Guns N' Roses - Welcome To The Jungle" },
  { id: "6Whgn_iE5uc", title: "Santana - Smooth (Stereo) ft. Rob Thomas" },
  { id: "roPQ_M3yJTA", title: "Nelly Furtado - I'm Like A Bird (Official Music Video)" },
  { id: "d4-1ASpdT1Y", title: "Bananarama - Venus (Official Video)" },
  { id: "s5BJXwNeKsQ", title: "Tom Petty And The Heartbreakers - Learning To Fly (Version 1)" },
  { id: "Wj7lL6eDOqc", title: "Lose Yourself (From "8 Mile" Soundtrack)" },
  { id: "ryde_5JlkSQ", title: "Sunday Bloody Sunday (Remastered 2008)" },
  { id: "rS7Va0sBYAM", title: "Smooth Operator (2011 Remastered)" },
  { id: "0qanF-91aJo", title: "BLACK SABBATH - "Paranoid" (Official Video)" },
  { id: "J9gKyRmic20", title: "Crowded House - Don't Dream It's Over (Official Music Video)" },
  { id: "vPzDTfIb0DU", title: "Faith No More - Easy (Official Music Video)" },
  { id: "uV5QdEt-deA", title: "Alone with You (2014 Remaster)" },
  { id: "1cQh1ccqu8M", title: "Nickelback - How You Remind Me" },
  { id: "6dOwHzCHfgA", title: "Cutting Crew - (I Just) Died In Your Arms (Official Music Video)" },
  { id: "6To0fvX_wFA", title: "Signed, Sealed, Delivered (I'm Yours)" },
  { id: "6p-lDYPR2P8", title: "Madonna - Material Girl (Official Video) [HD]" },
  { id: "ZbZSe6N_BXs", title: "Pharrell Williams - Happy (Video)" },
  { id: "ka9mCmx9Jhs", title: "Lisa Loeb - Stay (I Missed You)" },
  { id: "rBrd_3VMC3c", title: "Louis Armstrong - What A Wonderful World (Official Video)" },
  { id: "9SOryJvTAGs", title: "The B-52's - Love Shack (Official Music Video)" },
  { id: "ErHM7nLT04U", title: "Blister In The Sun - Violent Femmes: Audio Remastered" },
  { id: "PjsMnvqL7eY", title: "Silverchair - Tomorrow (US Version) (Official Video)" },
  { id: "6jLoxp8EmoM", title: "Am I Ever Gonna See Your Face Again : The Angels Live Melbourne 1988" },
  { id: "fSR3YgUcyU4", title: "Maxi Priest - Close To You" },
  { id: "nvlTJrNJ5lA", title: "Tom Petty And The Heartbreakers - I Won't Back Down (Official Music Video)" },
  { id: "aXJhDltzYVQ", title: "Prince & The Revolution - Let's Go Crazy (Official Music Video)" },
  { id: "k_ZPaQUS8W4", title: "KC & The Sunshine Band - That's the way (I like it) (retro video with edited music) HQ" },
  { id: "UFX3gQHIroU", title: "Janet Jackson - Escapade" },
  { id: "VVTds3za_5g", title: "the Cruel Sea - the Honeymoon Is Over video" },
  { id: "AR8D2yqgQ1U", title: "Spandau Ballet - True (HD Remastered)" },
  { id: "y2by810nulE", title: "Cold Chisel - Bow River [Official Video]" },
  { id: "39nPdQp69Gs", title: "Whitesnake - Here I Go Again - 2011 Remastered" },
  { id: "diYAc7gB-0A", title: "George Michael - Freedom! ’90 (Official Video)" },
  { id: "co6WMzDOh1o", title: "U2 - Beautiful Day (Official Music Video)" },
  { id: "MW6E_TNgCsY", title: "Everclear - Santa Monica (Official Music Video)" },
  { id: "niXNQ5dEcEA", title: "ABC" },
  { id: "U3sMjm9Eloo", title: "Tom Cochrane - Life Is A Highway (Official Video)" },
  { id: "jYx4Y52xAts", title: "Every Rose Has It's Thorn (Remastered 1996)" },
  { id: "Bkd5OQ8b0hQ", title: "Crowded House - Distant Sun" },
  { id: "qYkbTyHXwbs", title: "Rick Springfield - Jessie's Girl (Official Video)" },
  { id: "CHktgegKEwo", title: "Creed - With Arms Wide Open (New Version With Strings) from With Arms Wide Open: A Retrospective" },
  { id: "8SbUC-UaAxE", title: "Guns N' Roses - November Rain" },
  { id: "387ZDGSKVSg", title: "Tone Loc - Wild Thing" },
  { id: "bpA_5a0miWk", title: "Roxy Music - Avalon" },
  { id: "8zxA3y5UcbU", title: "The Stone Roses - Fools Gold (Remastered Version)" },
  { id: "N4bFqW_eu2I", title: "The Animals - House Of The Rising Sun (Music Video) [4K HD]" },
  { id: "0UIB9Y4OFPs", title: "DEF LEPPARD - "Pour Some Sugar On Me" (Official Music Video)" },
  { id: "IxuThNgl3YA", title: "Bruce Springsteen - Born to Run (Official Video)" },
  { id: "le1QF3uoQNg", title: "Theme From New York, New York (2008 Remastered)" },
  { id: "UG3VcCAlUgE", title: "Prince & The Revolution - When Doves Cry (Official Music Video)" },
  { id: "tkXNEmtf9tk", title: "Black Velvet by Alannah Myles" },
  { id: "7YHgZ1EDr1U", title: "Heroes (2002 Remaster)" },
  { id: "JuA-YPatiHU", title: "Unfinished Sympathy (Remastered 2006)" },
  { id: "eBShN8qT4lk", title: "Beastie Boys - (You Gotta) Fight For Your Right (To Party) (Official Music Video)" },
  { id: "qTA0RuZoIxM", title: "Aaliyah -Try Again (Original Video)" },
  { id: "ATMR5ettHz8", title: "Fleetwood Mac - Tusk (Official Music Video)" },
  { id: "4cia_v4vxfE", title: "Bachman Turner Overdrive - You Ain't Seen Nothing Yet 1974 Video Sound HQ" },
  { id: "oGpFcHTxjZs", title: "Tina Turner - What's Love Got To Do With It (Official Music Video) [HD Upgrade]" },
  { id: "rc0XEw4m-3w", title: "Stevie Wonder - Living for the City" },
  { id: "uMUQMSXLlHM", title: "Bob Marley & The Wailers - Buffalo Soldier (Official Music Video)" },
  { id: "UtvmTu4zAMg", title: "Fine Young Cannibals - She Drives Me Crazy (Official Video)" },
  { id: "yuTMWgOduFM", title: "Pulp - Common People" },
  { id: "HzZ_urpj4As", title: "Michael Jackson - The Way You Make Me Feel (Official Video)" },
  { id: "uO4lvUHr-r0", title: "Cold Chisel - Choir Girl [Official Video]" },
  { id: "cEgMousgsqQ", title: "I Ran (So Far Away) (Single Edit)" },
  { id: "zR9AlcgL6_0", title: "De La Soul - Me Myself and I (With Intro) (Official Music Video) [HD]" },
  { id: "59K2kF6o9Tk", title: "the rolling stones   brown sugar" },
  { id: "FTQbiNvZqaY", title: "Toto - Africa (Official HD Video)" },
  { id: "-MnELifX3sQ", title: "Beats International   Dub Be Good To Me" },
  { id: "WnOXYcO4zjg", title: "Divinyls - Boys In Town [HQ/1080p]" },
  { id: "EkHTsc9PU2A", title: "Jason Mraz - I'm Yours (Official Video) [4K Remaster]" },
  { id: "PUgkxLTMY3s", title: "Flowers - We Can Get Together (International Version)" },
  { id: "cGusP7aCCYc", title: "Arrested Development - People Everyday" },
  { id: "_mSmOcmk7uQ", title: "R.E.M. - Orange Crush (Official Music Video)" },
  { id: "Rd-oYM88niQ", title: "The Sports - Who Listens To The Radio (1978)" },
  { id: "_TGU35i8czo", title: "U2 - When Love Comes To Town (Official Music Video)" },
  { id: "n2_X4VTCoEo", title: "The Doors - Roadhouse Blues" },
  { id: "PobrSpMwKk4", title: "Grandmaster Flash & The Furious Five - The Message (Official Video)" },
  { id: "MHSGsIPMQIo", title: "Invisible Touch (2007 Remaster)" },
  { id: "X0P2DCVAFoM", title: "Baby Got Back" },
  { id: "k5hWWe-ts2s", title: "Meat Loaf - Two Out Of Three Ain't Bad (PCM Stereo)" },
  { id: "nqgUG_JVzCs", title: "Bad To The Bone" },
  { id: "sZLKtjATZt0", title: "Van Halen - Dreams" },
  { id: "7KEn0uOEILs", title: "Ziggy Stardust (2012 Remaster)" },
  { id: "tI-5uv4wryI", title: "Oasis - Champagne Supernova (Official Video)" },
  { id: "adVR3MT8fGg", title: "John Farnham - Age of Reason" },
  { id: "cBojbjoMttI", title: "The Sex Pistols - Anarchy In The U.K (official video)" },
  { id: "CvZwOA_62ew", title: "Similar Features" },
  { id: "x-xTttimcNk", title: "Comfortably Numb" },
  { id: "RxOBOhRECoo", title: "Elvis Presley - Suspicious Minds (Official Audio)" },
  { id: "Fpu5a0Bl8eY", title: "NENA | 99 Luftballons [1983] [Offizielles HD Musikvideo]" },
  { id: "yURRmWtbTbo", title: "Michael Jackson - Don't Stop 'Til You Get Enough (Official Video - Upscaled)" },
  { id: "qmOLtTGvsbM", title: "Toto - Rosanna (Official HD Video)" },
  { id: "rPrPNpzLHIk", title: "Big Audio Dynamite - The Globe" },
  { id: "jeYCyCaK_5k", title: "U2 - New Year's Day (Official Music Video)" },
  { id: "8O9P5Us_eVo", title: "I Wanna Be Sedated (1999 Remaster)" },
  { id: "z-GUjA67mdc", title: "The Stranglers - Golden Brown (Restored Music Video)" },
  { id: "AuPOwe-2EYA", title: "Dusty Springfield ~ i Just Don't Know What To Do With Myself (HQ)" },
  { id: "LV4gSOMVbT8", title: "Crazy Little Thing Called Love (Remastered 2011)" },
  { id: "Urdlvw0SSEc", title: "Alicia Keys - Fallin' (Official HD Video)" },
  { id: "izg5miONBhw", title: "Power And The Passion (Remastered)" },
  { id: "TzFnYcIqj6I", title: "Eurythmics, Annie Lennox, Dave Stewart - Here Comes The Rain Again (Remastered)" },
  { id: "MGxjIBEZvx0", title: "Bob Dylan - Subterranean Homesick Blues (Official HD Video)" },
  { id: "Hhnp3td-UHU", title: "Cold Chisel - Forever Now [Official Video]" },
  { id: "NrJEFrth27Q", title: "Mariah Carey - Emotions" },
  { id: "DVDCNmdi7QI", title: "Chaka Khan - I'm Every Woman (Official Music Video) [HD Remaster]" },
  { id: "def3ob2h-1s", title: "Iggy Pop - Real Wild Child (Wild One)" },
  { id: "zXt56MB-3vc", title: "UB40 - Red Red Wine (Official Video HD Remastered)" },
  { id: "6xckBwPdo1c", title: "Kate Bush - Babooshka - Official Music Video" },
  { id: "lLJf9qJHR3E", title: "Mumford and Sons - Little Lion Man" },
  { id: "eFjjO_lhf9c", title: "Bryan Adams - Summer Of '69 (Official Music Video)" },
  { id: "wHylQRVN2Qs", title: "Sting - Russians" },
  { id: "9iw_BE_X9sA", title: "The Rolling Stones - Emotional Rescue - OFFICIAL PROMO" },
  { id: "MDZsNksbw2Q", title: "Wild Cherry - Play That Funky Music" },
  { id: "Nwsyr5gAEuM", title: "You Am I - Berlin Chair" },
  { id: "R8AOAap6_k4", title: "Womack & Womack - Teardrops (Official Music Video)" },
  { id: "vo6D_tp3DeE", title: "Unforgettable" },
  { id: "YfpRm-p7qlY", title: "The Jam - Town Called Malice" },
  { id: "NNC0kIzM1Fo", title: "John Paul Young - Love Is In The Air (1978)" },
  { id: "lcOxhH8N3Bo", title: "Bonnie Tyler - Total Eclipse of the Heart (Turn Around) (Official Video)" },
  { id: "8WEtxJ4-sh4", title: "TLC - Waterfalls (Official HD Video)" },
  { id: "4dOsbsuhYGQ", title: "John Mellencamp - Hurts So Good (Official Music Video)" },
  { id: "1Z0jSNaIc4Q", title: "Streets of Philadelphia (Single Edit)" },
  { id: "WnIJiD4ol5A", title: "Love is all around  (1994 Four weddings and a funeral) Wet Wet Wet" },
  { id: "-r679Hhs9Zs", title: "The doors - Break On Through ( To The Other Side )" },
  { id: "nDK-wsdEhNE", title: "Pearl Jam - Better Man (Official Audio)" },
  { id: "wiqBlKnb91A", title: "Split Enz - I Got You (Official Video)" },
  { id: "IXdNnw99-Ic", title: "Pink Floyd - Wish You Were Here" },
  { id: "N61LHFFfiik", title: "Faith (Remastered 2006)" },
  { id: "cl3B_FTDKD0", title: "Talking Heads - And She Was (Official Video) [HD]" },
  { id: "yzLT6_TQmq8", title: "Propellerheads feat: Miss Shirley Bassey - History Repeating" },
  { id: "v0KpfrJE4zw", title: "Prince - Little Red Corvette (Official Music Video)" },
  { id: "SRvCvsRp5ho", title: "Bon Jovi - Wanted Dead Or Alive (Official Music Video)" },
  { id: "u1xrNaTO1bI", title: "Depeche Mode - Personal Jesus (Remastered)" },
  { id: "l482T0yNkeo", title: "AC/DC - Highway to Hell (Official Video)" },
  { id: "1TO48Cnl66w", title: "Dido - Thank You (Official Video)" },
  { id: "Emutat3_IP0", title: "John Farnham - Pressure Down" },
  { id: "Ef9QnZVpVd8", title: "The Rolling Stones - You Can’t Always Get What You Want (Official Video) [4K]" },
  { id: "VbD_kBJc_gI", title: "David Bowie - Let's Dance (Official Video)" },
  { id: "2BxVBziFvtU", title: "Regurgitator - Polyester Girl" },
  { id: "Tt1MqAZ9XHw", title: "The Carpenters - Top Of The World • TopPop" },
  { id: "0j6g_uUhH2c", title: "Steve Winwood - While You See A Chance" },
  { id: "wCDIYvFmgW8", title: "Fatboy Slim ft. Bootsy Collins - Weapon Of Choice [Official 4k Video]" },
  { id: "pHCdS7O248g", title: "Blondie - Rapture (Official Music Video)" },
  { id: "ftjEcrrf7r0", title: "U2 - One (Official Music Video)" },
  { id: "nvF5imxSaLI", title: "Bridge Over Troubled Water" },
  { id: "5boYiMktOvs", title: "DIVINYLS - Pleasure & Pain (1985) HD" },
  { id: "4jBuEGglsHM", title: "Layla (Acoustic; Live at MTV Unplugged, Bray Film Studios, Windsor, England, UK, 1/16/1992;..." },
  { id: "ApHM1ct4tdM", title: "Golden Years (2016 Remaster)" },
  { id: "IYoz2dpnuUQ", title: "Boom, Boom (Let’s Go Back To My Room) (Re-Recorded / Remastered)" },
  { id: "dS1ZW0FdoIU", title: "Kelly Clarkson - Miss Independent" },
  { id: "rmHDhAohJlQ", title: "The Prodigy - Breathe (Official Video)" },
  { id: "xuZA6qiJVfU", title: "The Cars - Drive (Official Music Video)" },
  { id: "4Ha-dtNXTM8", title: "Powderfinger - Pick You Up" },
  { id: "e__Pp4FxsjU", title: "You're The One That I Want (From “Grease”)" },
  { id: "duf-dofeoms", title: "Crowded House - It's Only Natural" },
  { id: "fe4EK4HSPkI", title: "MGMT - Kids (Official HD Video)" },
  { id: "xweiQukBM_k", title: "Paula Abdul, The Wild Pair - Opposites Attract" },
  { id: "3mbvWn1EY6g", title: "Motörhead – Ace Of Spades (Official Video)" },
  { id: "EKpHL483Bzw", title: "Somebody to Love (Remastered 2011)" },
  { id: "6EhG9giKZvo", title: "Don't You Want Me (2012 Remaster)" },
  { id: "dnwlHnvWH4Q", title: "Ike and Tina Turner shake your tail feather" },
  { id: "Eo-KmOd3i7s", title: "*NSYNC - Bye Bye Bye (Official Video)" },
  { id: "xXjyX9eb-DE", title: "The Day You Went Away (2007 Remastered)" },
  { id: "aOPEhg_dNPE", title: "Sherbet - Howzat • TopPop" },
  { id: "tbNlMtqrYS0", title: "The Proclaimers - I'm Gonna Be (500 Miles) (Official Music Video)" },
  { id: "FFOzayDpWoI", title: "Fiona Apple - Criminal (Official HD Video)" },
  { id: "Yem_iEHiyJ0", title: "Frankie Goes To Hollywood - Relax (Official Video)" },
  { id: "01aq2JWk3d0", title: "Killing Heidi - Weir (OFFICIAL AUSTRALIAN VIDEO)" },
  { id: "SkypZuY6ZvA", title: "Bee Gees - Night Fever" },
  { id: "mcUza_wWCfA", title: "The Cure - The Lovecats" },
  { id: "eVTXPUF4Oz4", title: "In The End [Official HD Music Video] - Linkin Park" },
  { id: "0FSE57u58rs", title: "One Night In Bangkok (Radio Edit / From “Chess” / Remastered 2016)" },
  { id: "eXV4WyQMHFM", title: "With A Little Help From My Friends" },
  { id: "DjcCQsRCHUs", title: "Hungry Like the Wolf (2009 Remaster)" },
  { id: "-1pMMIe4hb4", title: "Kate Bush - Wuthering Heights - Official Music Video - Version 1" },
  { id: "ynIHsHYaig0", title: "Sananda Maitreya - Wishing Well (Video)" },
  { id: "62v4y43D-3k", title: "We Are The Champions (Remastered 2011)" },
  { id: "5UXnulANF8g", title: "Dream Academy - "Life In A Northern Town" (Official Music Video)" },
  { id: "g94A1R8xHcQ", title: "One Love/People Get Ready (Extended Version) - Bob Marley & The Wailers" },
  { id: "eRhg7qPLeN8", title: "Sweet Dreams (Are Made of This) (2005 Remaster)" },
  { id: "mHONNcZbwDY", title: "Lionel Richie - Hello (Official Music Video)" },
  { id: "HyHNuVaZJ-k", title: "Gorillaz - Feel Good Inc. (Official Video)" },
  { id: "EPOIS5taqA8", title: "Kim Carnes - Bette Davis Eyes" },
  { id: "SsaFBNvhceA", title: "Kashmir (1990 Remaster)" },
  { id: "j_QLzthSkfM", title: "Devo - Whip It (Official Music Video) | Warner Vault" },
  { id: "0IA3ZvCkRkQ", title: "Mariah Carey - Hero (Official HD Video)" },
  { id: "CU3mc0yvRNk", title: "The Dandy Warhols - Bohemian Like You" },
  { id: "OdpTcvSn8HQ", title: "Concrete Blonde - Joey" },
  { id: "IwOfCgkyEj0", title: "Bob Dylan - Like a Rolling Stone (Official Audio)" },
  { id: "tSNxFGW09Mo", title: "Goanna - Solid Rock (Official Music Video)" },
  { id: "qiiyq2xrSI0", title: "Righteous Brothers - Unchained Melody (High Quality)" },
  { id: "AiCv9F_GRBA", title: "Divinyls ~ Science Fiction (Full Screen)" },
  { id: "0wBDDAZkNtk", title: "Jewel - Who Will Save Your Soul (Official HD Music Video)" },
  { id: "UrGw_cOgwa8", title: "Robert Palmer - Simply Irresistible (Official Video)" },
  { id: "IZBlqcbpmxY", title: "Jimi Hendrix - Voodoo Child (Slight Return)" },
  { id: "h_L4Rixya64", title: "Foo Fighters - Best Of You (Official HD Video)" },
  { id: "LJTk64tzduQ", title: "The Clash - Rock the Casbah (Remastered)" },
  { id: "W8r-tXRLazs", title: "The Buggles - Video Killed The Radio Star (Official Music Video)" },
  { id: "5ZfxwZ0y558", title: "Beautiful Boy (Darling Boy) (Stripped Down Mix, 2010)" },
  { id: "zTcu7MCtuTs", title: "Simply Red - If You Don't Know Me By Now (Official Video)" },
  { id: "jrwjiO1MCVs", title: "Jane's Addiction - Been Caught Stealing (Official Music Video) | Warner Vault" },
  { id: "pWxJEIz7sSA", title: "The Church - Under The Milky Way" },
  { id: "zDKO6XYXioc", title: "Boyz II Men - End Of The Road" },
  { id: "beINamVRGy4", title: "Third Eye Blind - Semi-Charmed Life (Official Music Video) [HD]" },
  { id: "SGyOaCXr8Lw", title: "The Rolling Stones - Start Me Up - Official Promo" },
  { id: "RNOTF-znQyw", title: "John Denver - Annie's Song (Official Audio)" },
  { id: "ZHwVBirqD2s", title: "Elton John - I'm Still Standing" },
  { id: "PyQFKmSYd9c", title: "[Lover] You Don't Treat Me No Good (Live)" },
  { id: "scif2vfg1ug", title: "The Cure - In Between Days" },
  { id: "10V_Z0_udjg", title: "Martika - Love...Thy Will Be Done" },
  { id: "gFVD3Wv9mpM", title: "Horror Movie (2015 Remaster)" },
  { id: "PsnYrH3BUP8", title: "Pat Benatar - All Fired Up (Official Music Video)" },
  { id: "SAFv2NEE-_c", title: "Midnight Oil - US Forces (Official Video)" },
  { id: "P5lmb5-tnM0", title: "Craig David - 7 Days (Official Video)" },
  { id: "WEQ0l_m3Xm0", title: "Macy Gray - I Try (Official Video)" },
  { id: "CmXWkMlKFkI", title: "Mötley Crüe - Kickstart My Heart (Official Music Video)" },
  { id: "3KFvoDDs0XM", title: "Oh, Pretty Woman" },
  { id: "63ZIf2H9S0E", title: "Tone loc - funky cold medina" },
  { id: "ySb1f9zWJkQ", title: "Foreigner - Cold As Ice (Official Music Video)" },
  { id: "w6iSeCTiU88", title: "Mustang Sally" },
  { id: "hLQl3WQQoQ0", title: "Adele - Someone Like You (Official Music Video)" },
  { id: "qlZqEFbVxgo", title: "Radio Ga Ga (Remastered 2011)" },
  { id: "DVq_gm8JsF8", title: "Doolin-Dalton / Desperado (Reprise) (2013 Remaster)" },
  { id: "dwDns8x3Jb4", title: "Daft Punk - Around the World (Official Audio)" },
  { id: "BshxCIjNEjY", title: "ABBA - Super Trouper" },
  { id: "3hxYDqhy2Vc", title: "Choirboys - Run To Paradise (Official Music Video)" },
  { id: "8f1z-nHvt3c", title: "The Doors - Hello, I Love You" },
  { id: "otCpCn0l4Wo", title: "M.C. Hammer - U Can't Touch This" },
  { id: "G_UXvcr22rM", title: "Charles & Eddie - Would I Lie To You" },
  { id: "CQ0ftoiIQxU", title: "Twisted Sister - We're not gonna take it (With Lyrics)" },
  { id: "VdQY7BusJNU", title: "Cyndi Lauper - Time After Time (Official HD Video)" },
  { id: "mYWqqMdd1X4", title: "Paul McCartney & Wings Band On The Run (2010 Remastered)." },
  { id: "1o4s1KVJaVA", title: "The Traveling Wilburys - Handle With Care (Official Video)" },
  { id: "lrpXArn3hII", title: "Bruce Springsteen - I'm On Fire (Official Video)" },
  { id: "-YriinrRGug", title: "Spice Girls - Who Do You Think You Are (Official Music Video)" },
  { id: "3YxaaGgTQYM", title: "Evanescence - Bring Me To Life (Official HD Music Video)" },
  { id: "Cv6tuzHUuuk", title: "The Bangles - Walk Like an Egyptian (Official Video)" },
  { id: "KwPxhWU1koE", title: "When a Man Loves a Woman (2000 Remaster)" },
  { id: "cmpRLQZkTb8", title: "Oasis - Don’t Look Back In Anger" },
  { id: "UAWcs5H-qgQ", title: "Ed Sheeran - The A Team [Official Music Video]" },
  { id: "rLVFk6zQx1E", title: "INXS - I Send A Message" },
  { id: "FOt3oQ_k008", title: "Rod Stewart - Sailing (Official Video)" },
  { id: "nPXqkjpXZ_k", title: "All Saints - Never Ever (US Version) (Official Music Video)" },
  { id: "h_D3VFfhvs4", title: "Michael Jackson - Smooth Criminal (Official Video)" },
  { id: "WM7-PYtXtJM", title: "Fleetwood Mac - Landslide (Official Music Video) [HD]" },
  { id: "w_U-jjGhLmU", title: "Australian Crawl - Reckless (Don't Be So...) (Official Audio)" },
  { id: "fZeuWoIBuo8", title: "Powderfinger - (Baby I've Got You) On My Mind [Official Video]" },
  { id: "YEAaLt0Qbl0", title: "Adam Ant - Antmusic (Official Video), Full HD (Digitally Remastered and Upscaled)" },
  { id: "p3j2NYZ8FKs", title: "Pet Shop Boys - West End Girls (Official Video) [HD REMASTERED]" },
  { id: "-0kcet4aPpQ", title: "Pink Floyd - Money (Official Music Video)" },
  { id: "uyGY2NfYpeE", title: "Sister Sledge - We Are Family (Official Music Video)" },
  { id: "WpYeekQkAdc", title: "The Black Eyed Peas - Where Is The Love? (Official Music Video)" },
  { id: "aGCdLKXNF3w", title: "Tears For Fears - Everybody Wants To Rule The World (Official Music Video)" },
  { id: "igvP806798U", title: "Born To Be Wild" },
  { id: "x3ov9USxVxY", title: "Madonna - Ray Of Light (Official Video) [HD]" },
  { id: "r3kQlzOi27M", title: "The Go-Go's - Our Lips Are Sealed" },
  { id: "Tv-FPvzwgoo", title: "April Sun in Cuba (Remastered 2006)" },
  { id: "6BODDyZRF6A", title: "Dexys Midnight Runners, Kevin Rowland - Come On Eileen (1982 Version)" },
  { id: "J7_bMdYfSws", title: "California Love (Original Version)" },
  { id: "x7qQmpK9b1M", title: "AC/DC - Jailbreak (Official Audio)" },
  { id: "8BYKpQ_6GbM", title: "Kim Wilde - Kids In America (1981) • TopPop" },
  { id: "KNZH-emehxA", title: "Shania Twain - You’re Still The One (Official Music Video)" },
  { id: "eFTLKWw542g", title: "Billy Joel - We Didn't Start the Fire (Official HD Video)" },
  { id: "YgSPaXgAdzE", title: "Beck - Loser (Official Music Video)" },
  { id: "dQsjAbZDx-4", title: "ABBA - Fernando (Official Music Video)" },
  { id: "7m94ip38UKs", title: "The Style Council - Shout To The Top" },
  { id: "GemKqzILV4w", title: "Snow Patrol - Chasing Cars (Official Video)" },
  { id: "GQQbjpomexo", title: "Seals & Crofts - Summer Breeze (Official Audio)" },
  { id: "2vjPBrBU-TM", title: "Sia - Chandelier (Official Video)" },
  { id: "ErvgV4P6Fzc", title: "Guns N' Roses - Patience" },
  { id: "AIOAlaACuv4", title: "Tracy Chapman - Fast Car (Official Music Video)" },
  { id: "XtJq56cp_dk", title: "Most People I Know Think That I'm Crazy  - Billy Thorpe and the Aztecs (Original single edit)" },
  { id: "trGX3ET3jTQ", title: "Mötley Crüe - Dr. Feelgood (Official Music Video)" },
  { id: "-N4jf6rtyuw", title: "Gnarls Barkley - Crazy (Official Video) [4K Remaster]" },
  { id: "SHAQlFq6TFg", title: "George Michael - Fastlove (Official Video)" },
  { id: "jjnmICxvoVY", title: "Savage Garden - I Knew I Loved You (Official Video)" },
  { id: "eH3giaIzONA", title: "Whitney Houston - I Wanna Dance With Somebody (Official 4K Video)" },
  { id: "LjhCEhWiKXk", title: "Bruno Mars - Just The Way You Are (Official Music Video)" },
  { id: "mTUhnIY3oRM", title: "Frankie Valli & The Four Seasons - December, 1963 (Oh, What a Night) (Official Music Video)" },
  { id: "MrHxhQPOO2c", title: "Jimmy Cliff - I Can See Clearly Now (Video Version)" },
  { id: "cbKNICg-REA", title: "Steve Winwood - Valerie (Official Video)" },
  { id: "0UnKPSmg3Ec", title: "The Cruel Sea - Better Get A Lawyer" },
  { id: "mW1dbiD_zDk", title: "P!nk - Get The Party Started (Official Video)" },
  { id: "lrKZNqIR2U0", title: "The Jacksons - Can You Feel It" },
  { id: "eTeg1txDv8w", title: "Crash Test Dummies - Mmm Mmm Mmm Mmm (Official Video)" },
  { id: "LlVI7ZNiFlI", title: "Roxette - The Look" },
  { id: "TR3Vdo5etCQ", title: "No Doubt - Don't Speak (Official 4K Music Video)" },
  { id: "LQiOA7euaYA", title: "Talking Heads - Road to Nowhere (Official Video)" },
  { id: "7SXKHiPQPhk", title: "Janet Jackson - Together Again (Official Music Video)" },
  { id: "LHcP4MWABGY", title: "U2 - Pride (In The Name Of Love) (Official Music Video)" },
  { id: "JIx2H-plXdU", title: "About A Girl (Remastered)" },
  { id: "AEyGZlBdkaA", title: "Pretenders - 2000 Miles (Official Music Video) [HD Remaster]" },
  { id: "tbIEwIwYz-c", title: "New Kids On The Block - You Got It (The Right Stuff) (Official Video)" },
  { id: "cAsNocbkXo8", title: "Forgotten Years (Remastered)" },
  { id: "VHlVdayWfOw", title: "INXS - By My Side (Official Music Video)" },
  { id: "KNIZofPB8ZM", title: "The Police - Don't Stand So Close To Me (Official Music Video)" },
  { id: "uq8PyyMbrYQ", title: "Hilltop Hoods - Chase That Feeling" },
  { id: "BqDjMZKf-wg", title: "The J. Geils Band - Centerfold (Official Music Video)" },
  { id: "na47wMFfQCo", title: "America - A Horse With No Name (Official Audio)" },
  { id: "Nntd2fgMUYw", title: "Eagle-Eye Cherry - Save Tonight" },
  { id: "9AjkUyX0rVw", title: "U.S.A. For Africa - We Are the World" },
  { id: "BR4yQFZK9YM", title: "P!nk - Stupid Girls" },
  { id: "r3Pr1_v7hsw", title: "Foreigner - I Want To Know What Love Is (Official Music Video)" },
  { id: "cVWOEx4Xdhs", title: "Royals" },
  { id: "K3SA5Z-cbC8", title: "The Cars - Shake It Up (Official Music Video)" },
  { id: "WDswiT87oo8", title: "Blur - Girls And Boys (Official Music Video)" },
  { id: "N_jJRrY6xYc", title: "Texas - I Don't Want A Lover (Official Video)" },
  { id: "3qVPNONdF58", title: "Blind Melon - No Rain" },
  { id: "3gOHvDP_vCs", title: "Justin Timberlake - SexyBack (Official Video) ft. Timbaland" },
  { id: "cJRP3LRcUFg", title: "The Smiths - This Charming Man (Official Music Video)" },
  { id: "j4jtIDaeaWI", title: "Suzanne Vega, DNA - Tom's Diner" },
  { id: "muhFxXce6nA", title: "Cheap Trick - The Flame" },
  { id: "YQHsXMglC9A", title: "Adele - Hello (Official Music Video)" },
  { id: "Rqnw5IfbZOU", title: "The Romantics - What I Like About You (Video)" },
  { id: "8qi7SlM1eDk", title: "The Whitlams - No Aphrodisiac (Official Video)" },
  { id: "sBW8Vnp8BzU", title: "The Waterboys - The Whole of the Moon [Official HD Remastered Video]" },
  { id: "C-Naa1HXeDQ", title: "Matchbox Twenty - 3AM (Official Video) [HD Remaster]" },
  { id: "y8OtzJtp-EM", title: "Immigrant Song (Remaster)" },
  { id: "hFDcoX7s6rE", title: "Queen - I Want It All (Official Video Remastered)" },
  { id: "uIbXvaE39wM", title: "Wilson Phillips - Hold On (Official Music Video)" },
  { id: "zvMFm5nKeUc", title: "Lemonheads - Mrs Robinson" },
  { id: "0QsTMqUfDDw", title: "Neil Diamond - Cherry, Cherry (Audio)" },
  { id: "btPJPFnesV4", title: "Survivor - Eye Of The Tiger (Official HD Video)" },
  { id: "ePWpolxEKiw", title: "Mark " Diesel" Lizotte - Tip Of My Tongue 1992" },
  { id: "LaTGrV58wec", title: "Gonna Make You Sweat (Everybody Dance Now) (Official HD Video)" },
  { id: "RB-RcX5DS5A", title: "Coldplay - The Scientist (Official 4K Video)" },
  { id: "4Fc67yQsPqQ", title: "Seal - Crazy (Official Music Video) [HD]" },
  { id: "yHpXjeEbpE4", title: "Steve Miller Band - Abracadabra (12'' Mix)" },
  { id: "h0ffIJ7ZO4U", title: "Dire Straits - Sultans Of Swing (Official Music Video)" },
  { id: "qSIOp_K5GMw", title: "Brandy & Monica - The Boy Is Mine (Official Video)" },
  { id: "4BijRaXScl8", title: "Let Me Entertain You" },
  { id: "gteuTLhO7N0", title: "The One I Love (Remastered 2012)" },
  { id: "Ixrje2rXLMA", title: "Dolly Parton - Jolene (Audio)" },
  { id: "d73tiBBzvFM", title: "Ace of Base - All That She Wants (Official Music Video)" },
  { id: "pjBkH9S76z8", title: "The Dead Heart (Remastered)" },
  { id: "POWsFzSFLCE", title: "Kylie Minogue - The Loco-motion - Official Video" },
  { id: "32Oc2d_3yEk", title: "Take It Easy (2013 Remaster)" },
  { id: "UfSBCgix5O0", title: "Baby Animals - 'Rush You'" },
  { id: "Yf_Lwe6p-Cg", title: "Wham! - Everything She Wants (Official Video)" },
  { id: "TOypSnKFHrE", title: "The Strokes - Last Nite (Official HD Video)" },
  { id: "z0qW9P-uYfM", title: "Elton John, Kiki Dee - Don't Go Breaking My Heart (with Kiki Dee)" },
  { id: "h3Yrhv33Zb8", title: "Aerosmith - Love In An Elevator" },
  { id: "7KbLoVKc8dE", title: "The Screaming Jets - Better (Official Music Video)" },
  { id: "jM7RcgZ1pLE", title: "Dragon - Rain (1983)" },
  { id: "ujPza2jSUtQ", title: "Stars On 54 - If You Could Read My Mind (Official Music Video)" },
  { id: "szbI1vu-cCc", title: "My Girl" },
  { id: "zI_SBAkdKzc", title: "David Gray - Babylon (Official Video)" },
  { id: "wacHJ81uGlM", title: "Grease 1978 - Greased Lightning (by John Travolta)" },
  { id: "-BiJKq7ynms", title: "Cold Chisel - You Got Nothing I Want [Official Video]" },
  { id: "pO1HC8pHZw0", title: "Frankie Goes To Hollywood - Two Tribes (Official Music Video)" },
  { id: "OAfxs0IDeMs", title: "Heart - All I Wanna Do Is Make Love To You" },
  { id: "gnhXHvRoUd0", title: "Kings Of Leon - Use Somebody (Official Video)" },
  { id: "0GLrn8JwJr0", title: "Diana King - Say A Little Prayer" },
  { id: "5hr64MxYpgk", title: "Mike + The Mechanics - The Living Years (Official HD Music Video)" },
  { id: "DL7-CKirWZE", title: "New Radicals - You Get What You Give (Official Music Video)" },
  { id: "4H5I6y1Qvz0", title: "Scissor Sisters - I Don't Feel Like Dancin'" },
  { id: "LTrk4X9ACtw", title: "Enya - Orinoco Flow (Official 4K Music Video)" },
  { id: "TSVHoHyErBQ", title: "Justin Timberlake - Rock Your Body (Official Video)" },
  { id: "UzWHE32IxUc", title: "Lenny Kravitz - American Woman" },
  { id: "8M_P_xX9Cmw", title: "The Go-Betweens - Streets of your Town HD" },
  { id: "UfmkgQRmmeE", title: "Van Morrison - Brown Eyed Girl (Official Audio)" },
  { id: "ZHh0V7UjVXI", title: "World Party - Ship of Fools" },
  { id: "QGJuMBdaqIw", title: "Katy Perry - Firework (Official Music Video)" },
  { id: "Lcb-Fsx_phM", title: "Foreigner - Urgent (Official Music Video)" },
  { id: "Kgjkth6BRRY", title: "Gwen Stefani - Hollaback Girl (Official Music Video)" },
  { id: "YjFW_p1PKbY", title: "Pop Muzik (Rhumba Calzada Remix)" },
  { id: "2MFlHGP0VAc", title: "TOTAL CONTROL - MOTELS ( studio version )" },
  { id: "4D35vfQ7eZg", title: "Robbie Williams - Come Undone" },
  { id: "9Ht5RZpzPqw", title: "blink-182 - All The Small Things (Official Music Video)" },
  { id: "qbAab1hTxN4", title: "Pretenders - Don't Get Me Wrong (Official Music Video)" },
  { id: "HaA3YZ6QdJU", title: "Billy Joel - Just the Way You Are (Official Audio)" },
  { id: "hwZNL7QVJjE", title: "Ben E. King - Stand By Me (Audio)" },
  { id: "CHatn3_UxEU", title: "Once in a Lifetime (2005 Remaster)" },
  { id: "4ka1Lgd3SAI", title: "Guy Sebastian - Battle Scars (Official Video) ft. Lupe Fiasco" },
  { id: "UaNGtgYwSsU", title: "Dolly Parton, Kenny Rogers - Islands In the Stream (Official Audio)" },
  { id: "hK5obmgq6u0", title: "Hanson - Where's The Love" },
  { id: "STugQ0X1NoI", title: "10cc - I'm Not In Love" },
  { id: "yVMF0d-y0fc", title: "Send Me An Angel 1983 Version (Re-Recorded / Remastered)" },
  { id: "MfmYCM4CS8o", title: "Jon Bon Jovi - Blaze Of Glory (Official Music Video)" },
  { id: "Im3JzxlatUs", title: "Gary Numan - Cars HD" },
  { id: "3KL9mRus19o", title: "Blackstreet - No Diggity (Official Music Video) ft. Dr. Dre, Queen Pen" },
  { id: "1eQWdpWjXlk", title: "Glory of Love" },
  { id: "PO2b3cggqs0", title: "Zebra - Official Video" },
  { id: "8yteMugRAc0", title: "The Boomtown Rats.  I Don't Like Mondays." },
  { id: "k2C5TjS2sh4", title: "Roxette - It Must Have Been Love (Official Music Video)" },
  { id: "eM213aMKTHg", title: "Lady Antebellum - Need You Now" },
  { id: "sl9DkcBreNw", title: "Tori Amos Professional Widow (It's Got To Be Big) [Armand's Star Trunk Funkin' Mix]" },
  { id: "l3LFML_pxlY", title: "Simon & Garfunkel - The Boxer (Audio)" },
  { id: "NKMtZm2YuBE", title: "Puff Daddy [feat. Faith Evans & 112] - I'll Be Missing You (Official Music Video)" },
  { id: "HasaQvHCv4w", title: "David Bowie & Mick Jagger - Dancing In The Street (Official Video)" },
  { id: "ah5gAkna3jI", title: "Gin Blossoms - Hey Jealousy (Official Music Video)" },
  { id: "SVOuYquXuuc", title: "YES - Owner of a Lonely Heart (Official Music Video)" },
  { id: "U56Ns66Qrb8", title: "Everything But The Girl - Missing (Official Music Video)" },
  { id: "rog8ou-ZepE", title: "Vanilla Ice - Ice Ice Baby (Official Music Video)" },
  { id: "_71w4UA2Oxo", title: "George Harrison - Got My Mind Set On You (Version II)" },
  { id: "a_426RiwST8", title: "The Black Keys - Lonely Boy [Official Music Video]" },
  { id: "nCBASt507WA", title: "Bryan Adams - Run To You" },
  { id: "5qm8PH4xAss", title: "50 Cent - In Da Club (Official Music Video)" },
  { id: "9b4F_ppjnKU", title: "Fleetwood Mac - Seven Wonders (Official Music Video)" },
  { id: "sLm3Khusq_8", title: "INXS - Don't Change (Official Music Video)" },
  { id: "lWA2pjMjpBs", title: "Rihanna - Diamonds" },
  { id: "3mbBbFH9fAg", title: "Soundgarden - Black Hole Sun" },
  { id: "_6FBfAQ-NDE", title: "Depeche Mode - Just Can't Get Enough (Remastered)" },
  { id: "iYqIF2XkqKU", title: "Paul Kelly - How To Make Gravy (Official Video)" },
  { id: "6e_7EkCZUzo", title: "BASTILLE - Dreams (ft. Gabrielle Aplin)" },
  { id: "YlIwHFGCrNY", title: "Rob Thomas - This Is How A Heart Breaks (Official Video)" },
  { id: "Gs069dndIYk", title: "Earth, Wind & Fire - September (Official HD Video)" },
  { id: "Sj_9CiNkkn4", title: "ABBA - Waterloo (Official Music Video)" },
  { id: "xy4FXhkm6Nw", title: "Young MC - Bust A Move" },
  { id: "3GwjfUFyY6M", title: "Kool & The Gang - Celebration" },
  { id: "JYlyghmTSIU", title: "Bernard Fanning - 'Wish You Well'" },
  { id: "9GkVhgIeGJQ", title: "The Cure - Boys Don't Cry" },
  { id: "QtTR-_Klcq8", title: "The Offspring - Pretty Fly (For A White Guy) (Official Music Video)" },
  { id: "RIjTq_OdFvo", title: "I'll Be There for You (Theme From "Friends")" },
  { id: "ZCOSPtyZAPA", title: "The Cult - She Sells Sanctuary HD" },
  { id: "lYfkl-HXfuU", title: "Jennifer Lopez - If You Had My Love (Official Video)" },
  { id: "XcATvu5f9vE", title: "Robert Palmer - Addicted To Love (Official Music Video)" },
  { id: "7Xf-Lesrkuc", title: "Train - Drops of Jupiter (Official Video)" },
  { id: "LiqPhGzOz1s", title: "O.P.P. (Re-Recorded)" },
  { id: "wBl2QGAIx1s", title: "Huey Lewis & The News - The Power Of Love (Official Music Video)" },
  { id: "WM8bTdBs-cw", title: "Metallica: One (Official Music Video)" },
  { id: "zQX2q6WCrbE", title: "Crystal Waters - 100% Pure Love" },
  { id: "XpEmHajlCt4", title: "Transvision Vamp - I Want Your Love" },
  { id: "RYnFIRc0k6E", title: "Limp Bizkit - Rollin' (Air Raid Vehicle)" },
  { id: "5YgevxRGXIU", title: "The Lovin' Spoonful - Summer in the City (Audio)" },
  { id: "HQt6jIKNwgU", title: "Savage Garden - I Want You" },
  { id: "kt0g4dWxEBo", title: "Rihanna, Kanye West, Paul McCartney - FourFiveSeconds" },
  { id: "CB40jEfzEQg", title: "Eric Carmen - Hungry Eyes (Dirty Dancing Soundtrack) (2018 Remastered)" },
  { id: "cjIvu7e6Wq8", title: "Missy Elliott - Work It [Official Music Video]" },
  { id: "dV3AziKTBUo", title: "Steve Miller Band - The Joker (Official Music Video)" },
  { id: "nNEb2k_EmMg", title: "Laura Branigan - Gloria (Official Music Video)" },
  { id: "bWXazVhlyxQ", title: "Rage Against The Machine - Killing In the Name (Official HD Video)" },
  { id: "dluHzQhLcME", title: "Sananda Maitreya - Sign Your Name" },
  { id: "JAHA4Jh5jkw", title: "Urge Overkill - Girl You'll Be a Woman Soon" },
  { id: "cMOKamtpUA8", title: "Pretenders - Back on the Chain Gang (Official Music Video)" },
  { id: "mzJj5-lubeM", title: "Red Hot Chili Peppers - Scar Tissue [Official Music Video] [HD UPGRADE]" },
  { id: "t1DWBKk5xHQ", title: "Kylie Minogue - Spinning Around (Official Video)" },
  { id: "I4qh_9vH1Ww", title: "David Lee Roth - Just Like Paradise" },
  { id: "N-aK6JnyFmk", title: "The Mamas & The Papas - California Dreamin'" },
  { id: "UH1CMCtV4to", title: "Bryan Ferry - Slave To Love (Official Music Video)" },
  { id: "Jwtyn-L-2gQ", title: "The Rolling Stones - Sympathy For The Devil (Official Video) [4K]" },
  { id: "P0K1nSsfSDo", title: "Underneath the Radar" },
  { id: "agrXgrAgQ0U", title: "Fergie - Big Girls Don't Cry (Personal) (Official Music Video)" },
  { id: "ESIKf_wtLnM", title: "Rebel Yell (Remastered 1999)" },
  { id: "C9v8fStNnhk", title: "Moonshadow" },
  { id: "fFnOfpIJL0M", title: "Tom Petty And The Heartbreakers - Refugee" },
  { id: "gGdGFtwCNBE", title: "The Killers - Mr. Brightside (Official Music Video)" },
  { id: "UMVjToYOjbM", title: "The Traveling Wilburys - End Of The Line (Official 4K Music Video)" },
  { id: "k04tX2fvh0o", title: "Guns N' Roses - Knockin' On Heaven's Door (Visualizer)" },
  { id: "cNEdxZURTaI", title: "ABC - The Look Of Love" },
  { id: "D-NvQ6VJYtE", title: "Jamiroquai - Cosmic Girl (Video)" },
  { id: "tpKCqp9CALQ", title: "The Chemical Brothers - Hey Boy Hey Girl (Official Music Video)" },
  { id: "CYpn8yUnX_c", title: "I Bet You Look Good On The Dancefloor" },
  { id: "Ln6WQqRDrCo", title: "Hootie & The Blowfish - Only Wanna Be with You (Official Music Video) [HD]" },
  { id: "RijB8wnJCN0", title: "Cypress Hill - Insane In The Brain (Official HD Video)" },
  { id: "QmqYQRkszGA", title: "U2 - Angel Of Harlem (Official Music Video)" },
  { id: "uZD8HKVKneI", title: "Glenn Frey - The Heat Is On (From "Beverly Hills Cop" Soundtrack)" },
  { id: "7QU1nvuxaMA", title: "Audioslave - Like a Stone (Official Video)" },
  { id: "yXQViqx6GMY", title: "Mariah Carey - All I Want For Christmas Is You (Official Video)" },
  { id: "5X-Mrc2l1d0", title: "Michael Jackson - Rock With You (Official Video - Upscaled)" },
  { id: "hSWbpVjwQGM", title: "The Soup Dragons - I'm Free" },
  { id: "717TcuN_-oo", title: "The Bee Gees - More Than A Woman (RSO Records 1977)" },
  { id: "CZe9YxJNs48", title: "The Presets - My People (Official Video)" },
  { id: "mLqHDhF-O28", title: "Thirty Seconds To Mars - Closer To The Edge" },
  { id: "-n3sUWR4FV4", title: "Billy Ocean - When the Going Gets Tough, the Tough Get Going (Official Video)" },
  { id: "1VQ_3sBZEm0", title: "Foo Fighters - Learn To Fly (Official HD Video)" },
  { id: "dls_cBmUt7Q", title: "Faith Hill - "This Kiss" (Official Video)" },
  { id: "Fo6aKnRnBxM", title: "Gerry Rafferty - Baker Street (Official Video)" },
  { id: "_lK4cX5xGiQ", title: "Tenacious D - Tribute (Official Video)" },
  { id: "ql1EnjVYrZM", title: "Julian Lennon - Saltwater (1991, Official Music Video)" },
  { id: "dIhRZNHuWlo", title: "Rose Tattoo - We Can't Be Beaten (1982)" },
  { id: "wV1FrqwZyKw", title: "Lady Gaga - Born This Way (Official Music Video)" },
  { id: "BJKpUH2kJQg", title: "Oasis - Supersonic (Official HD Remastered Video)" },
  { id: "siwpn14IE7E", title: "Kenny Loggins - Danger Zone (Official Video - Top Gun)" },
  { id: "jSUPaTF-wN8", title: "Birds of Tokyo - Plans (Official video)" },
  { id: "pNmWeUiZqEE", title: "Since U Been Gone (Jason Nevins Radio Edit)" },
  { id: "qae25976UgA", title: "Warren Zevon - Werewolves Of London (Official Music Video) [HD]" },
  { id: "PTFwQP86BRs", title: "Nine Inch Nails - Closer (Director's Cut)" },
  { id: "M0pWejAnLUQ", title: "Slice of Heaven - Dave Dobbyn" },
  { id: "j4JBrd-xAc0", title: "Ignition (Remix)" },
  { id: "UmPgMc3R8zg", title: "Stevie Nicks - Edge of Seventeen (Official Music Video)" },
  { id: "oofSnsGkops", title: "James Blunt - You're Beautiful (Official Music Video) [4K]" },
  { id: "CL8mWlIxzqw", title: "Axiom - A Little Ray of Sunshine (Classic Rock)" },
  { id: "Tb7-y0s_vUI", title: "Together In Electric Dreams (Remastered 2003)" },
  { id: "Lrle0x_DHBM", title: "Earth, Wind & Fire - Let's Groove (Official HD Video)" },
  { id: "0Gl2QnHNpkA", title: "Backstreet Boys - As Long As You Love Me (Official HD Video)" },
  { id: "mmo3HFa2vjg", title: "Public Enemy - Fight The Power (Official Music Video)" },
  { id: "69RdQFDuYPI", title: "Bob Marley - Is This Love (Official Music Video)" },
  { id: "rXwMrBb2x1Q", title: "The Jimi Hendrix Experience - Hey Joe (Official Audio)" },
  { id: "bKxodgpyGec", title: "Cee Lo Green - Forget You" },
  { id: "Ijk4j-r7qPA", title: "Franz Ferdinand - Take Me Out (Video)" },
  { id: "cvChjHcABPA", title: "ABBA - SOS (Official Music Video)" },
  { id: "cT6y24Ddn0w", title: "Father Figure (Remastered - featured in 'Babygirl')" },
  { id: "EPmTGFg06zA", title: "Orchestral Manoeuvres In The Dark - If You Leave (Official Music Video)" },
  { id: "vRxxh3CzJXk", title: "Baby Did a Bad Bad Thing - Official Music Video" },
  { id: "l7vRSu_wsNc", title: "Prince & The Revolution - Raspberry Beret (Official Music Video)" },
  { id: "dvgZkm1xWPE", title: "Coldplay - Viva La Vida (Official Video)" },
  { id: "CXFsWAkLoXQ", title: "Alice Cooper- Schools out" },
  { id: "SECVGN4Bsgg", title: "Men At Work - Who Can It Be Now? (Video Version)" },
  { id: "Ee_uujKuJMI", title: "Green Day - American Idiot [Official Music Video] [4K Upgrade]" },
  { id: "fayL1WTR1Go", title: "The Small Faces - Itchykoo Park (1967)" },
  { id: "NJWIbIe0N90", title: "P!nk - Who Knew (Official Video)" },
  { id: "1wv4yTSFlHI", title: "Phil Collins - Sussudio (2016 Remaster)" },
  { id: "d1acEVmnVhI", title: "The Smashing Pumpkins - Disarm" },
  { id: "c_BcivBprM0", title: "Patti Smith Group - Because the Night (Official Audio)" },
  { id: "NvR60Wg9R7Q", title: "Bon Jovi - Bed Of Roses (Official Music Video)" },
  { id: "aXgSHL7efKg", title: "CHIC - Le Freak (Official Music Video)" },
  { id: "OSFGK9HlEto", title: "Christine Anu My Island Home" },
  { id: "IOD0DQ7AN5Q", title: "The Sugarhill Gang - Rapper's Delight (Single Version) [Audio HQ]" },
  { id: "tuK6n2Lkza0", title: "Jet - Are You Gonna Be My Girl (Official Music Video)" },
  { id: "sfCLt0kTd5E", title: "EMF - Unbelievable (Official Music Video) HD" },
  { id: "1RHBAd5YUR8", title: "The Communards - Don't Leave Me This Way (with Sarah Jane Morris) [Official Video]" },
  { id: "6NXnxTNIWkc", title: "4 Non Blondes - What's Up (Official Music Video)" },
  { id: "FIF7wKJb2iU", title: "George Benson - Give Me The Night (Official Music Video) [HD Remaster]" },
  { id: "GHUql3OC_uU", title: "Come Out and Play" },
  { id: "d-diB65scQU", title: "Bobby McFerrin - Don't Worry Be Happy (Official Music Video)" },
  { id: "bx3s99FNXzI", title: "LeAnn Rimes - Cant Fight The Moonlight (Official Music Video)" },
  { id: "fPO76Jlnz6c", title: "Coolio - Gangsta's Paradise (feat. L.V.) [Official Music Video]" },
  { id: "Nnjh-zp6pP4", title: "AC/DC - High Voltage (Official Video)" },
  { id: "BnO3nijfYmU", title: "Robbie Williams - Rock DJ" },
  { id: "AAZQaYKZMTI", title: "Billy Idol - White Wedding Pt 1" },
  { id: "WkSbyewt44Y", title: "Jimmy Barnes - Aint No Mountain High Enough (1992)" },
  { id: "qeQANBPQPGc", title: "Your Move / Give Peace A Chance Medley" },
  { id: "N5EnGwXV_Pg", title: "John Mayer - Your Body Is a Wonderland (Official HD Video)" },
  { id: "TB54dZkzZOY", title: "Soul II Soul - Back To Life (However Do You Want Me) (Official Music Video)" },
  { id: "BZzsi1y82Y8", title: "Vic Reeves and The Wonder Stuff - Dizzy" },
  { id: "txapREGWHp0", title: "Fairground Attraction - Perfect" },
  { id: "rhzmNRtIp8k", title: "Foo Fighters - Times Like These (Official HD Video)" },
  { id: "FfHtiCVA5d8", title: "Boom! Shake the Room - DJ Jazzy Jeff & The Fresh Prince" },
  { id: "u7yWc3uPpqs", title: "22 royal philharmonic orchestra bat out of hell meatloaf" },
  { id: "mJPDJRLxHek", title: "Alex Lloyd - Amazing (Official Video)" },
  { id: "zkHOVJINRD8", title: "M People - Moving on Up (Official Video)" },
  { id: "88sARuFu-tc", title: "Bronski Beat - Smalltown Boy (Official Video)" },
  { id: "YuKfiH0Scao", title: "Bill Withers - Ain't No Sunshine (Official Audio)" },
  { id: "EBQCbPbPS8E", title: "BOOM CRASH OPERA - The Best Thing" },
  { id: "lbnoG2dsUk0", title: "Ginuwine - Pony" },
  { id: "tKjZuykKY1I", title: "The Darkness - I Believe In A Thing Called Love (Official Music Video) [HD]" },
  { id: "hOllF3TgAsM", title: "Bush - Glycerine" },
  { id: "wy709iNG6i8", title: "Goodbye Yellow Brick Road (Remastered 2014)" },
  { id: "a748-dgSB10", title: "Two Princes" },
  { id: "cdNRiZ0kwR8", title: "California Girls (Remix/Remastered 2001)" },
  { id: "jsoOtwPXpGE", title: "Kylie Minogue - On A Night Like This (Official Video)" },
  { id: "xvaEJzoaYZk", title: "Steve Earle - Copperhead Road (Official Music Video)" },
  { id: "RCN6eRVav5k", title: "Rock and Roll (Remaster)" },
  { id: "vx-Lzo9NxAQ", title: "Kiss from a Rose" },
  { id: "uJ_1HMAGb4k", title: "Vance Joy - 'Riptide' Official Video" },
  { id: "ZwRXxtwcJus", title: "Jet (2010 Remaster)" },
  { id: "PGNiXGX2nLU", title: "Dead Or Alive - You Spin Me Round (Like a Record) (Official Video)" },
  { id: "gY2ekm_krNU", title: "Robbie Williams - Better Man" },
  { id: "OzQKECQgjW8", title: "Moving Pictures - What About Me (1982)" },
  { id: "rZwSqX6J5hs", title: "Fuel - Shimmer (Official HD Video)" },
  { id: "YDkk2oxiZhw", title: "Tonight's the Night (Gonna Be Alright) (2009 Remaster)" },
  { id: "LlZydtG3xqI", title: "TLC - Creep (Official HD Video)" },
  { id: "9n3A_-HRFfc", title: "Cher - If I Could Turn Back Time (Official Video)" },
  { id: "WZF8G7ssoUk", title: "Spiderbait - Black Betty (Official Audio)" },
  { id: "DvxxdZpMFHg", title: "Rockin' in the Free World" },
  { id: "PHzOOQfhPFg", title: "No Doubt - Just A Girl" },
  { id: "XcKKzC3chKw", title: "Errol (Remastered)" },
  { id: "P6zaCV4niKk", title: "Yusuf / Cat Stevens - Father & Son" },
  { id: "ifARMmcqhD8", title: "Joan Armatrading-Drop The Pilot" },
  { id: "-eHJ12Vhpyc", title: "Elvis Presley - Hound Dog (Official Audio)" },
  { id: "IBtlTHYRScY", title: "INXS - Listen Like Thieves" },
  { id: "YlUKcNNmywk", title: "Red Hot Chili Peppers - Californication (Official Music Video) [HD UPGRADE]" },
  { id: "nfk6sCzRTbM", title: "Paul Young - Everytime You Go Away (Official Video)" },
  { id: "X2W3aG8uizA", title: "Bob Marley - Get Up Stand Up [HQ Sound]" },
  { id: "f3y8jf01UY8", title: "Sunshine Of Your Love" },
  { id: "hCuMWrfXG4E", title: "Billy Joel - Uptown Girl (Official Video)" },
  { id: "VVtD4qMy5Hc", title: "The Living End - Prisoner Of Society (Video)" },
  { id: "5BmEGm-mraE", title: "Creedence Clearwater Revival: Bad Moon Rising" },
  { id: "xQ04WbgI9rg", title: "Foo Fighters - All My Life (Official HD Video)" },
  { id: "nighr1Od-2E", title: "Old Time Rock'n'Roll" },
  { id: "nW9Cu6GYqxo", title: "Bonnie Raitt - I Can't Make You Love Me" },
  { id: "pOLDBKPIAmA", title: "Tequila Sunrise" },
  { id: "42BBdzzgPNM", title: "Green Day - Longview [Official Music Video] (4K Upgrade)" },
  { id: "zpOULjyy-n8", title: "REO Speedwagon - Can't Fight This Feeling (Official HD Video)" },
  { id: "gOMhN-hfMtY", title: "Eminem - Stan (Long Version) ft. Dido" },
  { id: "4LdZAK2Rfkg", title: "The Angels Take A Long Line" },
  { id: "si3dBlNdifE", title: "Crowded House - Four Seasons In One Day" },
  { id: "RBumgq5yVrA", title: "Passenger | Let Her Go (Official Video)" },
  { id: "yMoDJ4HWWaE", title: "Panama 2015 Remaster" },
  { id: "fgT9zGkiLig", title: "Incubus - Drive" },
  { id: "cntvEDbagAw", title: "The Specials - A Message To You Rudy (Official Music Video)" },
  { id: "6YziZ1FlAWs", title: "George Michael - Amazing (Official Video)" },
  { id: "_PVjcIO4MT4", title: "The Jimi Hendrix Experience - Foxey Lady (Miami Pop 1968)" },
  { id: "EFMD7Usflbg", title: "Kiss - Rock And Roll All Nite (From Kiss eXposed)" },
  { id: "FMrIy9zm7QY", title: "Fatboy Slim - Rockafeller Skank [Official Video]" },
  { id: "LSGl3d4KOMk", title: "Sting - If You Love Somebody Set Them Free" },
  { id: "0J2QdDbelmY", title: "The White Stripes - Seven Nation Army (Official Music Video)" },
  { id: "v0CYB5V9e64", title: "Hole - Malibu (Official Music Video)" },
  { id: "h6wvTU01X6w", title: "INXS - Burn For You" },
  { id: "uj0wPrN_Y_4", title: "Ike & Tina Turner - River Deep Mountain High (original 1966 promo, edited)" },
  { id: "YZQWTnrJMS0", title: "ICEHOUSE - Hey, Little Girl" },
  { id: "450p7goxZqg", title: "John Legend - All of Me (Official Video)" },
  { id: "VuRCQ4VRZsU", title: "Jimmy Barnes and The Badloves   The Weight" },
  { id: "DtVBCG6ThDk", title: "Elton John - Rocket Man (Official Music Video)" },
  { id: "PJwt2dxx9yg", title: "Joe Jackson - Steppin' Out" },
  { id: "7-SSa-D1i-M", title: "Instant Karma! (We All Shine On)" },
  { id: "qdflARH06dY", title: "Kasey Chambers - Not Pretty Enough (Video)" },
  { id: "7kfYOGndVfU", title: "Moondance (2013 Remaster)" },
  { id: "pB-5XG-DbAA", title: "Sam Smith - Stay With Me (Official Music Video)" },
  { id: "t4LWIP7SAjY", title: "(Patti) LaBelle - Lady Marmalade (1975) HD 0815007" },
  { id: "BRcs_OzQb14", title: "The Black Crowes - Hard To Handle" },
  { id: "7hx4gdlfamo", title: "Kenny Rogers - The Gambler" },
  { id: "nLAWPrCUQQ0", title: "Los Lobos - La Bamba (Original Videoclip)" },
  { id: "GeZZr_p6vB8", title: "Nelly - Hot In Herre (Official Music Video)" },
  { id: "xCmA1uC0r9A", title: "Bullet With Butterfly Wings (Remastered 2012)" },
  { id: "CVsLEI-hCXw", title: "Long Train Runnin'" },
  { id: "PgRafRp-P-o", title: "Marc Cohn - Walking in Memphis (Official Music Video)" },
  { id: "hlVBg7_08n0", title: "MACKLEMORE & RYAN LEWIS - SAME LOVE feat. MARY LAMBERT (OFFICIAL VIDEO)" },
  { id: "mPQPdYttl7U", title: "Ballroom Blitz" },
  { id: "58mXxWuUqYw", title: "Grinspoon - Chemical Heart (Official Video)" },
  { id: "kemivUKb4f4", title: "Weezer - Buddy Holly (Official Music Video)" },
  { id: "1lWJXDG2i0A", title: "Tom Petty - Free Fallin'" },
  { id: "HKGjCPBSG38", title: "Sonny & Cher - I Got You Babe (Official Audio)" },
  { id: "JsntlJZ9h1U", title: "Daryl Hall & John Oates - Private Eyes (Official HD Video)" },
  { id: "enhQYHxoNMY", title: "Ben Lee - Catch My Disease (Official Music Video)" },
  { id: "NRtvqT_wMeY", title: "Soul Asylum - Runaway Train (Official HD Video)" },
  { id: "QYHxGBH6o4M", title: "Rick James - Super Freak (Official Music Video)" },
  { id: "IKnnh8VDULs", title: "Jackson Browne - Running On Empty - OFFICIAL VIDEO MONTAGE" },
  { id: "aENX1Sf3fgQ", title: "The Police - Every Little Thing She Does Is Magic (Official Music Video)" },
  { id: "T6QKqFPRZSA", title: "Lauryn Hill - Doo Wop (That Thing) (Official HD Video)" },
  { id: "bawlZLHMEas", title: "Thin Lizzy - The Boys Are Back In Town (HQ)" },
  { id: "z8rQ575DWD8", title: "U2 - Desire (Official Music Video)" },
];
