const playlist = [
  { id: "fJ9rUzIMcZQ", title: "Queen - Bohemian Rhapsody" },
  { id: "1w7OgIMMRc4", title: "Guns N' Roses - Sweet Child O' Mine" },
  { id: "hTWKbfoikeg", title: "Nirvana - Smells Like Teen Spirit" },
  { id: "EcPsB6PwaiE", title: "John Lennon - Imagine" },
  { id: "tbkOZTSvrHs", title: "John Farnham - You're the Voice" },
  { id: "X791IzOwt3Q", title: "Led Zeppelin - Stairway to Heaven" }, // assumed based on title
  { id: "GChhRrU6BJU", title: "AC/DC - It's a Long Way to the Top (If You Wanna Rock 'N' Roll)" },
  { id: "uQy3y9Ox0gE", title: "Michael Jackson - Thriller" },
  { id: "MSSxnv1_J2g", title: "The Rolling Stones - (I Can't Get No) Satisfaction" }, // assumed based on title
  { id: "xFrGuyw1V8s", title: "ABBA - Dancing Queen" },
  { id: "lDK9QqIzhwk", title: "Bon Jovi - Livin' on a Prayer" },
  { id: "dnqxbdnzlhw", title: "The Easybeats - Friday on My Mind" },
  { id: "s__rX_WL100", title: "Madonna - Like a Virgin" },
  { id: "oMfjgQ8ptrE", title: "The Beach Boys - Good Vibrations" }, // assumed based on title
  { id: "rm9coqlk8fY", title: "Bob Dylan - Knockin' on Heaven's Door" },
  { id: "izGwDsrQ1eQ", title: "George Michael - Careless Whisper" },
  { id: "e3-5YC_oHjE", title: "U2 - I Still Haven't Found What I'm Looking For" },
  { id: "6FOUqQt3Kg0", title: "Aretha Franklin - Respect" },
  { id: "3JWTaaS7LdU", title: "Whitney Houston - I Will Always Love You" },
  { id: "8UVNT4wvIGY", title: "Gotye - Somebody That I Used to Know (feat. Kimbra)" },
  { id: "AQOlwMKpmvQ", title: "Crowded House - Better Be Home Soon" },
  { id: "qoX6AKuYWL8", title: "The Doors - Light My Fire" },
  { id: "XfR9iY5y94s", title: "Men at Work - Down Under" },
  { id: "vU05Eksc_iM", title: "Oasis - Wonderwall" },
  { id: "H-kA3UtBj4M", title: "Marvin Gaye - What's Going On" },
  { id: "inKlN0ScObA", title: "Cold Chisel - Khe Sanh" },
  { id: "fNFzfwLM72c", title: "Bee Gees - Stayin' Alive" },
  { id: "4m1EFMoRFvY", title: "Beyoncé - Single Ladies (Put a Ring on It)" },
  { id: "gJLIiF15wjQ", title: "Spice Girls - Wannabe" },
  { id: "0CFuCYNx-1g", title: "Stevie Wonder - Superstition" },
  { id: "c18441Eh_WE", title: "Kylie Minogue - Can't Get You Out of My Head" },
  { id: "GLvohMXgcBo", title: "Red Hot Chili Peppers - Under the Bridge" },
  { id: "_wO8toxinoc", title: "Meat Loaf - You Took the Words Right Out of My Mouth" },
  { id: "JmcA9LIIXWw", title: "Culture Club - Karma Chameleon" },
  { id: "luwAMFcc2f8", title: "Robbie Williams - Angels" },
  { id: "0xGPi-Al3zQ", title: "Fleetwood Mac - Rhiannon" }, // assumed based on title
  { id: "CD-E-LDc384", title: "Metallica - Enter Sandman" },
  { id: "CpKyFTYvhpU", title: "Elvis Presley - Don't Be Cruel" },
  { id: "F93ywiGMDnQ", title: "INXS - Need You Tonight" },
  { id: "iYYRH4apXDo", title: "David Bowie - Space Oddity" },
  { id: "3MMXjunSx80", title: "Jeff Buckley - Last Goodbye" },
  { id: "PIb6AZdTr-A", title: "Cyndi Lauper - Girls Just Want to Have Fun" },
  { id: "HrxX9TBj2zY", title: "Pink Floyd - Another Brick in the Wall, Part Two" },
  { id: "psTq_J-JwNI", title: "Yothu Yindi - Treaty" },
  { id: "y5ecvBaqHBk", title: "Don McLean - American Pie" },
  { id: "0-EF60neguk", title: "Sinéad O'Connor - Nothing Compares 2 U" },
  { id: "j13oJajXx0M", title: "Carly Simon - You're So Vain" },
  { id: "TLV4_xaYynY", title: "The Jimi Hendrix Experience - All Along the Watchtower" },
  { id: "CnQ8N1KacJc", title: "Green Day - Good Riddance (Time of Your Life)" },
  { id: "StKVS0eI85I", title: "Blondie - Call Me" },
  { id: "OPf0YbXqDm0", title: "Mark Ronson - Uptown Funk (feat. Bruno Mars)" },
  { id: "nqxVMLVe62U", title: "The Jacksons - Blame It on the Boogie" },
  { id: "uq-gYOrU8bA", title: "Paul Simon - You Can Call Me Al" },
  { id: "5-hDK76bIps", title: "Hunters & Collectors - Throw Your Arms Around Me" },
  { id: "gxEPV4kolz0", title: "Billy Joel - Piano Man" },
  { id: "t3TPmPOrDEk", title: "Jimmy Barnes - Working Class Man" },
  { id: "eJO5HU_7_1w", title: "Eminem - The Real Slim Shady" },
  { id: "zuuObGsB0No", title: "Joy Division - Love Will Tear Us Apart" },
  { id: "WQnAxOQxQIU", title: "Savage Garden - Truly Madly Deeply" },
  { id: "CduA0TULnow", title: "Britney Spears - Oops!... I Did It Again" },
  { id: "bbr60I0u2Ng", title: "The Knack - My Sharona" },
  { id: "xwtdhWltSIg", title: "R.E.M. - Losing My Religion" },
  { id: "yYcyacLRPNs", title: "Elton John - Tiny Dancer" },
  { id: "EPhWR4d3FJQ", title: "Bruce Springsteen - Born in the U.S.A." },
  { id: "ydrtF45-y-g", title: "Salt-N-Pepa - Let's Talk About Sex" },
  { id: "oQfAZVsz6KM", title: "Daddy Cool - Eagle Rock" },
  { id: "HM_eb0vVo0k", title: "Powderfinger - My Happiness" },
  { id: "A_MjCqQoLLA", title: "The Beatles - Hey Jude" },
  { id: "qM0zINtulhM", title: "Pearl Jam - Alive" },
  { id: "rYEDA3JcQqw", title: "Adele - Rolling in the Deep" },
  { id: "zNW2XkvaL6U", title: "Midnight Oil - Beds Are Burning" }, // assumed based on known track
  { id: "zFYEYRcjK2g", title: "Radiohead - Creep" }, // assumed based on title
  { id: "BWEKw5xG69M", title: "Take That - Back for Good" },
  { id: "3mkidP2OUCk", title: "Icehouse - Great Southern Land" },
  { id: "d020hcWA_Wg", title: "Coldplay - Clocks" },
  { id: "WnrE0yN2uLY", title: "Gloria Gaynor - I Will Survive" }, // assumed based on common attribution
  { id: "oKOtzIo-uYw", title: "Fugees - Killing Me Softly" },
  { id: "OMOGaugKpzs", title: "The Police - Every Breath You Take" },
  { id: "CoOp12ayIVg", title: "Eric Clapton - Tears in Heaven" }, // assumed based on known acoustic version
  { id: "KCjMZMxNr-0", title: "Duran Duran - Girls on Film" },
  { id: "wBVJFGxyxgE", title: "Russell Morris - The Real Thing" },
  { id: "NHozn0YXAeE", title: "Hanson - MMMBop" },
  { id: "eBG7P-K-r1Y", title: "Foo Fighters - Everlong" },
  { id: "pIgZ7gMze7A", title: "Wham! - Wake Me Up Before You Go-Go" },
  { id: "KUmZp8pR1uc", title: "Amy Winehouse - Rehab" },
  { id: "8LhCd1W2V0Q", title: "Lenny Kravitz - Are You Gonna Go My Way" },
  { id: "tdkROH7Exyg", title: "The Who - My Generation" },
  { id: "1lyu1KKwC74", title: "The Verve - Bitter Sweet Symphony" },
  { id: "47P3bzefCVI", title: "Silverchair - Straight Lines" },
  { id: "NPcyTyilmYY", title: "Alanis Morissette - You Oughta Know" },
  { id: "Zi_XLOBDo_Y", title: "Michael Jackson - Billie Jean" },
  { id: "lp-EO5I60KA", title: "Ed Sheeran - Thinking Out Loud" },
  { id: "4F_RCWVoL4s", title: "Neil Diamond - Sweet Caroline" },
  { id: "wTP2RUD_cL0", title: "Dire Straits - Money for Nothing" },
  { id: "SSbBvKaM6sk", title: "Blur - Song 2" },
  { id: "n0pcM30pjgQ", title: "Split Enz - Message to My Girl" },
  { id: "fDxzQJaA228", title: "George Michael & Aretha Franklin - I Knew You Were Waiting (For Me)" },
  { id: "4RdATJ_6870", title: "Ben E. King - Stand by Me" }, // assumed from title
  { id: "djV11Xbc914", title: "a-ha - Take On Me" },
  { id: "oG6fayQBm9w", title: "Lou Reed - Walk on the Wild Side" },
  { id: "VlWiQ69DGE0", title: "Them - Gloria (feat. Van Morrison)" },
  { id: "t1CvS7aOMa4", title: "The Rolling Stones - Angie" },
  { id: "ZR-eTR3Dcps", title: "Paul Kelly - Dumb Things" },
  { id: "E2Ru4_A8INU", title: "Midnight Oil - Blue Sky Mine" },
  { id: "MYU3F8uUGiw", title: "Elton John - Candle in the Wind" },
  { id: "ujNeHIo7oTE", title: "U2 - With or Without You" },
  { id: "unfzfe8f9NI", title: "ABBA - Mamma Mia" },
  { id: "SUGlWCCVA4M", title: "Cold Chisel - Cheap Wine" },
  { id: "RaNEVlz89f8", title: "Daryl Braithwaite - The Horses" },
  { id: "PWgvGjAhvIw", title: "Outkast - Hey Ya!" },
  { id: "FJ-r0bilzhU", title: "Elvis Presley - In the Ghetto" },
  { id: "ZG_k5CSYKhg", title: "Faith No More - Epic" },
  { id: "ViwtNLUqkMY", title: "Beyoncé - Crazy in Love (feat. JAY Z)" },
  { id: "v2AC41dglnM", title: "AC/DC - Thunderstruck" },
  { id: "IHknoSQZibU", title: "Madonna - Holiday" },
  { id: "ag8XcMG1EX4", title: "Crowded House - Weather with You" },
  { id: "5oWyMakvQew", title: "Fleetwood Mac - Dreams" },
  { id: "aaYpQVsifvI", title: "David Bowie - Changes" },
  { id: "Jne9t8sHpUc", title: "Alanis Morissette - Ironic" },
  { id: "wqPlb5PLBvg", title: "The Who - You Better You Bet" },
  { id: "vHXjcdNIN-Q", title: "The Doors - L.A. Woman" },
  { id: "KrZHPOeOxQQ", title: "Bon Jovi - You Give Love a Bad Name" },
  { id: "hajBdDM2qdg", title: "Marvin Gaye - I Heard It Through the Grapevine" },
  { id: "ZhIsAZO5gl0", title: "Kiss - I Was Made for Lovin' You" },
  { id: "ltrMfT4Qz5Y", title: "Kenny Loggins - Footloose" },
  { id: "ma2lQ3c-FuA", title: "Stevie Wright - Evie (Let Your Hair Hang Down)" },
  { id: "JZjWGsAUnkI", title: "Backstreet Boys - Everybody (Backstreet's Back)" },
  { id: "wpqm-05R2Jk", title: "The Avalanches - Since I Left You" },
  { id: "vabnZ9-ex7o", title: "Nirvana - Come as You Are" },
  { id: "DfDt-KKHIaU", title: "The Police - Roxanne" },
  { id: "LPn0KFlbqX8", title: "Cyndi Lauper - True Colors" },
  { id: "2ROiU9kOHeE", title: "Crowded House - Fall at Your Feet" },
  { id: "MpMwMDqOprc", title: "The Saints - (I'm) Stranded" },
  { id: "RF0HhrwIwp0", title: "Kings of Leon - Sex on Fire" },
  { id: "oRdxUFDoQe0", title: "Michael Jackson - Beat It" },
  { id: "pTdihu-mp90", title: "James Brown - I Got You (I Feel Good)" },
  { id: "Lo2qQmj0_h4", title: "AC/DC - You Shook Me All Night Long" },
  { id: "MQcPB1WkISI", title: "Living Colour - Love Rears Its Ugly Head" },
  { id: "H0Ww6TkAwoQ", title: "Pat Benatar - Love Is a Battlefield" },
  { id: "_W44NZvHc9I", title: "Alicia Keys - Empire State of Mind (Part II) Broken Down" },
  { id: "R9L1O426uF8", title: "Elton John - Don't Let the Sun Go Down on Me" },
  { id: "PTULqzrhBWA", title: "INXS - Original Sin" },
  { id: "Jv4et3RIMcg", title: "The Kinks - Lola" },
  { id: "1tLYYSofs3U", title: "Queen - Another One Bites the Dust" },
  { id: "FrLequ6dUdM", title: "TLC - No Scrubs" },
  { id: "hic-dnps6MU", title: "The Rolling Stones - Miss You" },
  { id: "94bdMSCdw20", title: "Joni Mitchell - Big Yellow Taxi" },
  { id: "qQvr2eF5zMM", title: "The Church - The Unguarded Moment" },
  { id: "wv-34w8kGPM", title: "Divinyls - I Touch Myself" },
  { id: "wMsazR6Tnf8", title: "Joan Jett & The Blackhearts - I Love Rock 'n' Roll" },
  { id: "TYQzIw0zat0", title: "Roy Orbison - You Got It" }, // assumed based on known title
  { id: "lDpnjE1LUvE", title: "Nick Cave & The Bad Seeds - Where the Wild Roses Grow (feat. Kylie Minogue)" },
  { id: "XpqqjU7u5Yc", title: "Bee Gees - How Deep Is Your Love" },
  { id: "H9tEvfIsDyo", title: "Prince & The Revolution - Kiss" },
  { id: "etviGf1uWlg", title: "Deee-Lite - Groove Is in the Heart" },
  { id: "Rbm6GXllBiw", title: "Guns N' Roses - Paradise City" },
  { id: "HoS1Fr9G46I", title: "Cold Chisel - When the War Is Over" },
  { id: "UvEmwYg6aFw", title: "Queen - We Will Rock You" },
  { id: "CdqoNKCCt7A", title: "Simple Minds - Don't You (Forget About Me)" },
  { id: "iG7XifX5JhY", title: "Led Zeppelin - Whole Lotta Love" },
  { id: "TxcDTUMLQJI", title: "U2 - Mysterious Ways" },
  { id: "PivWY9wn5ps", title: "Michael Jackson - Man in the Mirror" },
  { id: "umAurdHLNzU", title: "Alicia Bridges - I Love the Nightlife" },
  { id: "god7hAPv8f0", title: "Earth, Wind & Fire - Boogie Wonderland" },
  { id: "towUVNELZBI", title: "Australian Crawl - The Boys Light Up" },
  { id: "8AHCfZTRGiI", title: "Johnny Cash - Hurt" },
  { id: "wo1OwRTRKRk", title: "Elton John - Bennie and the Jets" },
  { id: "JAwk7yBQxDs", title: "George Michael - Too Funky" },
  { id: "4BQLE_RrTSU", title: "Bill Medley & Jennifer Warnes - (I've Had) The Time of My Life" },
  { id: "eLZghQtxeSA", title: "John Fogerty - Lookin' Out My Backdoor" },
  { id: "2nXGPZaTKik", title: "Culture Club - Do You Really Want to Hurt Me" },
  { id: "jsjdjWGDvFk", title: "AC/DC - Dirty Deeds Done Dirt Cheap" },
  { id: "Y0pdQU87dc8", title: "Bryan Adams - (Everything I Do) I Do It for You" },
  { id: "vTv9z0ynDWc", title: "Skyhooks - Ego Is Not a Dirty Word" },
  { id: "tAGnKpE4NCI", title: "Metallica - Nothing Else Matters" },
  { id: "0H6re3PCP3E", title: "Pretenders - Brass in Pocket" },
  { id: "gHTcQB_4AFw", title: "Hot Chocolate - Every 1's a Winner" },
  { id: "OqSrEhuWrgY", title: "Jimmy Barnes - Good Times" },
  { id: "UrIiLvg58SY", title: "Extreme - More Than Words" },
  { id: "fAb8Q9X2xAc", title: "Blondie - The Tide Is High" },
  { id: "XEjLoHdbVeE", title: "ABBA - Gimme! Gimme! Gimme! (A Man After Midnight)" },
  { id: "bpZvg_FjL3Q", title: "Bob Dylan - Hurricane" },
  { id: "JnfyjwChuNU", title: "Red Hot Chili Peppers - By the Way" },
  { id: "4aXkA6X_zsA", title: "David Bowie - China Girl" },
  { id: "V6hQ9HSKlIE", title: "Tracy Chapman - Give Me One Reason" },
  { id: "PNbBDrceCy8", title: "The Who - Who Are You" },
  { id: "oXqPjx94YMg", title: "k.d. lang - Constant Craving" },
  { id: "7qFfFVSerQo", title: "Radiohead - High and Dry" },
  { id: "6Ejga4kJUts", title: "The Cranberries - Zombie" },
  { id: "oAZLgsDRUv4", title: "Dusty Springfield - Son of a Preacher Man" },
  { id: "CS9OO0S5w2k", title: "Village People - YMCA" },
  { id: "G333Is7VPOg", title: "Madonna - Papa Don't Preach" },
  { id: "Wm54XyLwBAk", title: "Oasis - Morning Glory" },
  { id: "XZVpR3Pk-r8", title: "Soft Cell - Tainted Love" },
  { id: "TFIrKWg89r4", title: "Split Enz - I See Red" },
  { id: "WfunypXsBO4", title: "U2 - Where the Streets Have No Name" },
  { id: "CxKWTzr-k6s", title: "Pearl Jam - Even Flow" },
  { id: "oe2hdbft5-U", title: "Bob Marley & The Wailers - I Shot the Sheriff" },
  { id: "Z0GFRcFm-aY", title: "R.E.M. - It's the End of the World As We Know It (And I Feel Fine)" },
  { id: "bgghy8gmCvQ", title: "Meat Loaf - I'd Do Anything for Love (But I Won't Do That)" },
  { id: "T0spQCw35D4", title: "Nick Cave & The Bad Seeds - The Ship Song" },
  { id: "xvqeSJlgaNk", title: "The Monkees - Daydream Believer" },
  { id: "e7tWqyM3r-g", title: "The Clash - Should I Stay or Should I Go" },
  { id: "A_J2bcNx3Gw", title: "Grease Cast - Summer Nights" }, // assumed based on context
  { id: "yugLWxoX7qQ", title: "Eurythmics & Aretha Franklin - Sisters Are Doin' It for Themselves" },
  { id: "JkK8g6FMEXE", title: "Aerosmith - I Don't Want to Miss a Thing" },
  { id: "LrjHz5hrupA", title: "Elvis Costello & The Attractions - Oliver's Army" },
  { id: "LvdLovAaYzM", title: "Martika - Toy Soldiers" },
  { id: "uSD4vsh1zDA", title: "The Black Eyed Peas - I Gotta Feeling" },
  { id: "lelsyP9qL2I", title: "Cold Chisel - Saturday Night" },
  { id: "-35W_FWCT9Q", title: "Lynyrd Skynyrd - Sweet Home Alabama" },
  { id: "eOUtsybozjg", title: "Bon Jovi - Bad Medicine" },
  { id: "6jC9Insyzgc", title: "Tina Arena - Chains" },
  { id: "6vQpW9XRiyM", title: "Bruce Springsteen - Glory Days" },
  { id: "ZSM3w1v-A_Y", title: "Timbaland - Apologize (feat. OneRepublic)" },
  { id: "ruTMp4_sy1E", title: "The Rolling Stones - Jumpin' Jack Flash" },
  { id: "9jK-NcRmVcw", title: "Europe - The Final Countdown" },
  { id: "RCaWyhDFYCk", title: "Michael Jackson - Black or White" },
  { id: "Ye7FKc1JQe4", title: "Tears for Fears - Shout" },
  { id: "HyMm4rJemtI", title: "David Bowie - Ashes to Ashes" },
  { id: "FoEPrbdfmT4", title: "INXS - What You Need" },
  { id: "6vwNcNOTVzY", title: "Kanye West - Gold Digger (feat. Jamie Foxx)" },
  { id: "0TMoc959LCA", title: "Irene Cara - Flashdance... What a Feeling" },
  { id: "cBMXQrW3VNA", title: "Queen - Killer Queen" },
  { id: "oadhHk2xs6c", title: "Chris Isaak - Wicked Game" }, // assumed
  { id: "rUnktL_ZZgo", title: "Midnight Oil - King of the Mountain" },
  { id: "HsC_SARyPzk", title: "Phil Collins - A Groovy Kind of Love" },
  { id: "LerRV-CGeFU", title: "Paul Kelly - Before Too Long" },
  { id: "4B_UYYPb-Gk", title: "RUN DMC & Aerosmith - Walk This Way" },
  { id: "Y5fBdpreJiU", title: "The Killers - Somebody Told Me" },
  { id: "ClbmWkbocoY", title: "Sheryl Crow - All I Wanna Do" },
  { id: "GlPlfCy1urI", title: "Elton John - Your Song" },
  { id: "4aeETEoNfOg", title: "The Smashing Pumpkins - 1979" },
  { id: "-crgQGdpZR0", title: "ABBA - Take a Chance on Me" },
  { id: "iQI5fdVCvlU", title: "Hunters & Collectors - Holy Grail" },
  { id: "eHUUMEv2j94", title: "The Moody Blues - Nights in White Satin" },
  { id: "q-4TkRMEK7Y", title: "Van Halen - Jump" },
  { id: "-oqAU5VxFWs", title: "Counting Crows - Mr. Jones" },
  { id: "PiZHNw1MtzI", title: "AC/DC - Who Made Who" },
  { id: "hv_zJrO_ptk", title: "INXS - Devil Inside" },
  { id: "uE-itlGNap4", title: "Pseudo Echo - Funkytown" },
  { id: "Mr_uHJPUlO8", title: "Red Hot Chili Peppers - Give It Away" },
  { id: "jQvUBf5l7Vw", title: "Iggy Pop - Lust for Life" },
  { id: "rblt2EtFfC4", title: "Prince - 1999" },
  { id: "79fzeNUqQbQ", title: "Madonna - Like a Prayer" },
  { id: "2b_KfAGiglc", title: "Janet Jackson - That's the Way Love Goes" },
  { id: "cvn6eYJh-0c", title: "Robbie Williams & Kylie Minogue - Kids" },
  { id: "y2bVIBwpCTA", title: "The Jackson 5 - I Want You Back" },
  { id: "9lApaQC58r8", title: "Eurythmics - Who's That Girl" },
  { id: "c4BLVznuWnU", title: "Ed Sheeran - Lego House" },
  { id: "hEmH1EgJbEs", title: "En Vogue & Salt-N-Pepa - Whatta Man" },
  { id: "WGoDaYjdfSg", title: "The Jimi Hendrix Experience - Purple Haze" },
  { id: "ovo6zwv6DX4", title: "Lionel Richie - Dancing on the Ceiling" },
  { id: "qKn7XAMNV-g", title: "Missy Higgins - Scar" },
  { id: "Yv3dvVw6p5c", title: "U2 - Sweetest Thing" }, // assumed artist based on song
  { id: "K1b8AhIsSYQ", title: "Starship - We Built This City" },
  { id: "-Ro8-ngA8gs", title: "Chaka Khan - Ain't Nobody" },
  { id: "CvBfHwUxHIk", title: "Rihanna - Umbrella (feat. JAY-Z)" },
  { id: "WyBKzBtaKWM", title: "Crowded House - Something So Strong" },
  { id: "HBcq5EzBcmQ", title: "Robert Palmer & UB40 - I'll Be Your Baby Tonight" },
  { id: "xJeWySiuq1I", title: "Ultravox - Vienna" },
  { id: "lfVAJNqWw84", title: "The Beatles - The Long and Winding Road" },
  { id: "HAkHqYlqops", title: "Matchbox Twenty - Push" },
  { id: "_3eC35LoF4U", title: "Talking Heads - Burning Down the House" },
  { id: "GC5E8ie2pdM", title: "Tina Turner - The Best" },
  { id: "ruAi4VBoBSM", title: "Fatboy Slim - Praise You" },
  { id: "AIBv2GEnXlc", title: "INXS - Never Tear Us Apart" },
  { id: "SsmVgoXDq2w", title: "The Bangles - Manic Monday" },
  { id: "IUFOVu1CurM", title: "Icehouse - Electric Blue" },
  { id: "BjvfIJstWeg", title: "The Cure - Close to Me" },
  { id: "6s9il0BTI4I", title: "Kylie Minogue - Confide in Me" },
  { id: "aXK71H8c-l0", title: "Queen - I Want to Break Free" },
  { id: "0hGhl7ki3HM", title: "Fleetwood Mac - Don't Stop" },
  { id: "boJhWtw-6Gg", title: "Bruce Springsteen - Hungry Heart" },
  { id: "ML9h3I5Uktw", title: "GANGgajang - Sounds of Then (This Is Australia)" },
  { id: "1uYWYWPc9HU", title: "Radiohead - Karma Police" },
  { id: "k0W_ybghFzg", title: "U2 - All I Want Is You" },
  { id: "-DlMoJ2V6uk", title: "Michael Jackson - Bad" },
  { id: "qQzdAsjWGPg", title: "Frank Sinatra - My Way" },
  { id: "FYH8DsU2WCk", title: "New Order - Blue Monday" },
  { id: "yKNxeF4KMsY", title: "Coldplay - Yellow" },
  { id: "04v-SdKeEpE", title: "George Harrison - My Sweet Lord" },
  { id: "Bx51eegLTY8", title: "Berlin - Take My Breath Away" },
  { id: "RqQn2ADZE1A", title: "Aerosmith - Janie's Got a Gun" },
  { id: "0aqLwHP4y6Q", title: "Toni Basil - Mickey" },
  { id: "u7K72X4eo_s", title: "Massive Attack - Teardrop" },

];
